### ISSUE TITLE
Broken ARC build - missing ./cmd/actionsmetricsserver

### ISSUE THREAD

**Issue by isarkis** [actions/actions-runner-controller#2090]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

acbce4b

### Helm Chart Version

N/A

### CertManager Version

N/A

### Deployment Method

Kustomize

### cert-manager installation

N/A

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
N/A
```

### To Reproduce

```markdown
Clone latest code and try to build ARC like so:

VERSION=controller1 RUNNER_TAG=runner1 make docker-buildx
```

### Describe the bug

It looks like https://github.com/actions/actions-runner-controller/commit/300e93c59d3b2c4cb0883a7657199235dc025719#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557 broke ARC build, the docker image doesn't build because ./cmd/actionsmetricsserver is missing.

### Describe the expected behavior

Docker image should build.

### Whole Controller Logs

```shell
N/A
```

### Whole Runner Pod Logs

```shell
N/A
```

**Comment by mumoshu** [comment]
@isarkis Thanks a lot for testing and reporting it! We're going to add it via #2099
