### ISSUE TITLE
Add more labels to metrics-server metrics

### ISSUE THREAD

**Issue by hamishforbes** [actions/actions-runner-controller#2176]
### What would you like added?

The [metrics](https://github.com/actions/actions-runner-controller/blob/0324658a3fad79237b5da9c21a3ce6f6cc9a4429/pkg/actionsmetrics/metrics.go) emitted from the metrics-server currently only include `job` and `runs_on` labels.

I think `repository` is required at a minimum for this to be useful, and probably `organisation` too?

[edit]
Actually `workflow_name` is probably required as well
Although workflow name has only [just](https://github.com/google/go-github/pull/2630) been added to the go-github library!
[/edit]

### Why is this needed?

If I have 2 Github repos (`A` and `B`) and they both have a workflow jobs called `test` and `build` (for example) the metrics aren't differentiated, I have no idea how many test jobs ran for repo A vs repo B, only how many ran for all of them.

We would get metrics like:

```
github_workflow_jobs_completed_total{job_name="test",runs_on="ubuntu-latest"} 123
github_workflow_jobs_completed_total{job_name="build",runs_on="ubuntu-latest"} 123
```

To be useful we'd want:

```
github_workflow_jobs_completed_total{organisation="foo",repository="A",job_name="test",runs_on="ubuntu-latest"} 23
github_workflow_jobs_completed_total{organisation="bar,repository="B",job_name="test",runs_on="ubuntu-latest"} 100
github_workflow_jobs_completed_total{organisation="foo",repository="A",job_name="build",runs_on="ubuntu-latest"} 23
github_workflow_jobs_completed_total{organisation="bar",repository="B",job_name="build",runs_on="ubuntu-latest"} 100
```

**Comment by dongho-jung** [comment]
+1 fyi I'm workarounding this by using [hook](https://github.com/actions/runner/blob/main/docs/adrs/1751-runner-job-hooks.md) as follows but it would be more awesome if it's supported in metrics-server natively

**_NOTE: BEFORE USE BELOW SNIPPET, [READ THIS COMMENT](https://github.com/actions/actions-runner-controller/issues/2176#issuecomment-1457199341)!_**

```bash
#!/bin/bash -x
kubectl -n actions-runner-system label pod $RUNNER_NAME \
  actor=$(echo $GITHUB_ACTOR | sed 's/[^a-zA-Z0-9_.-]//g') \
  repo=$(echo $GITHUB_REPOSITORY | cut -d/ -f2 | sed 's/[^a-zA-Z0-9_.-]//g') \
  job=$(echo $GITHUB_JOB | sed 's/[^a-zA-Z0-9_.-]//g') \
  runner=$(echo $RUNNER_NAME | sed 's/[^a-zA-Z0-9_.-]//g') \
  sha=$GITHUB_SHA \
  attempt=$GITHUB_RUN_ATTEMPT \
  run_id=$GITHUB_RUN_ID
```

**_NOTE: BEFORE USE ABOVE SNIPPET, [READ THIS COMMENT](https://github.com/actions/actions-runner-controller/issues/2176#issuecomment-1457199341)!_**

**Comment by timansky** [comment]
it will be great to include branch name also

**Comment by mumoshu** [comment]
@hamishforbes @0xF4D3C0D3 @timansky Hey! `organization` and `repository` have been already added via https://github.com/actions/actions-runner-controller/pull/2218. We might be adding `owner` for non-org repos via https://github.com/actions/actions-runner-controller/pull/2225. That said, can we close this once we add `branch` and `workflow_name`?

**Comment by mumoshu** [comment]
I'm a bit concerned about cardinality explosion https://github.com/actions/actions-runner-controller/pull/2218#discussion_r1112470069 but perhaps it won't be a huge problem as long as you won't have hundreds of workflows running against hundreds of branches... (which would result in dozens of thousands more time-series generated and stored.

**Comment by mumoshu** [comment]
@hamishforbes @0xF4D3C0D3 @timansky It would be great if you could also check https://github.com/actions/actions-runner-controller/issues/2359 by @kkaresz-tw and add 👍, comments, and/or feedback!

**Comment by mumoshu** [comment]
@0xF4D3C0D3 Hey! Thanks for sharing your workaround. It does look great and helps many folks not yet using a custom build of ARC (as we didn't cut even a new release that contains #2218 yet...)

After carefully reviewing your hook script, I realized you included `runner`, `sha`, and `run_id` of the workflow job. I'm a bit afraid of those resulting in **"3 new time series" instead of "3 new metrics in the existing time series"**. Didn't it cause regressions on your Prometheus or managed metrics store performance/cost/etc?

You may already know, but here's an excerpt from the official Prometheus documentation for your convenience:

> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
> https://prometheus.io/docs/practices/naming/

**Comment by dongho-jung** [comment]
@mumoshu Thanks! for letting me know that. I didn't know that risk D: fortunately, I'm in not that big team so I haven't experience any regressions yet, it would be problem later indeed. To be honest, I was using prometheus as a black box or a cargo cult 😳

(I could check the cardinality by `go tool pprof -symbolize=remote -inuse_space http://{prometheus_endpoint}/debug/pprof/heap`)

**Comment by hamishforbes** [comment]
> I'm a bit concerned about cardinality explosion [#2218 (comment)](https://github.com/actions/actions-runner-controller/pull/2218#discussion_r1112470069) but perhaps it won't be a huge problem as long as you won't have hundreds of workflows running against hundreds of branches... (which would result in dozens of thousands more time-series generated and stored.

Sorry haven't had a chance to look at any of this stuff again yet.
But, I don't think there's likely to be much of a cardinality issue with just repo/owner, its not really unbounded as you can only have as many combinations as your have repos.
Branch is more likely to be problematic, which is why I didn't include it in my PR, it is technically unbounded.

Ideally I think these labels would be configurable ([kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/cli-arguments.md) is a high-profile example of this with `--metric-labels-allowlist`)
If you are running ARC across thousands of repos and the cardinality of having repo/owner in the labels is a problem then it would be nice to simply turn them off.
Likewise if you are running on a couple of repos and only have a few branches active at once then having branch as a label is probably very helpful

I have branch enable in my custom build too, its definitely good for being able to catch when changes in a branch are causing long build/test runs!

**Comment by mumoshu** [comment]
Thank you for your comments everyone! I've just merged #2225. It includes `workflow_name` suggested in https://github.com/actions/actions-runner-controller/issues/2176#issuecomment-1457179959.

It doesn't include `branch` yet as it turned out [go-github does not expose it](https://github.com/google/go-github/blame/9bfbc0063c544ba14ebd5298242f4ba9bdbe8c6f/github/actions_workflow_jobs.go#LL31). I'll try to submit a tiny pull request to add that- once that's merged we are ready to work on adding `branch` 😄

**Comment by kkaresz-tw** [comment]
@mumoshu regarding the missing `branch` field in `WorkflowJob` in go-github, I opened a PR: https://github.com/google/go-github/issues/2762 in case you wanted to follow its release.

**Comment by th-le** [comment]
Hi @mumoshu  I open a PR https://github.com/actions/actions-runner-controller/pull/2549 to use the branch_name in the metrics according to the changes from @kkaresz-tw above

**Comment by syaldram** [comment]
Hello I am wondering if it is possible to add timestamp `gha_job_execution_duration_seconds_sum` metric. I am trying to create a table in grafana that can give me a timestamp on which job was started, worfklow_ref, repo and etc.
