### ISSUE TITLE
аа

### ISSUE THREAD

**Issue by lanbz1k** [actions/actions-runner-controller#2200]
### What would you like added?

*A clear and concise description of what you want to happen.*

Note: Feature requests to integrate vendor specific cloud tools (e.g. `awscli`, `gcloud-sdk`, `azure-cli`) will likely be rejected as the Runner image aims to be vendor agnostic.

### Why is this needed?

*A clear and concise description of any alternative solutions or features you've considered.*

### Additional context

*Add any other context or screenshots about the feature request here.*

**Comment by Link-** [comment]
Spam.
