### ISSUE TITLE
Missing RBAC role and bindings for the Actions Metrics Server RBAC proxy

### ISSUE THREAD

**Issue by jjacobelli** [actions/actions-runner-controller#2212]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.0

### Helm Chart Version

0.22.0

### CertManager Version

1.10.1

### Deployment Method

Helm

### cert-manager installation

Cert-manager is installed and working fine

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
N/A
```

### To Reproduce

```markdown
Deploy the controller using Helm with the Actions Metrics Server enabled:

[...]
actionsMetricsServer:
    enabled: true
actionsMetrics:
  proxy:
    enabled: true
[...]
```

### Describe the bug

Helm is missing the RBAC role and role binding for the `kube-rbac-proxy` used by the Actions Metrics Server which is causing the following error:
```
I0125 13:39:34.273513       1 request.go:1154] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"tokenreviews.authentication.k8s.io is forbidden: User \"system:serviceaccount:arc-rapidsai:arc-rapidsai-actions-metrics-server\" cannot create resource \"tokenreviews\" in API group \"authentication.k8s.io\" at the cluster scope","reason":"Forbidden","details":{"group":"authentication.k8s.io","kind":"tokenreviews"},"code":403}
```

### Describe the expected behavior

Helm should deploy a role and a role binding for the  `kube-rbac-proxy` used by the Actions Metrics Server

### Whole Controller Logs

```shell
N/A
```

### Whole Runner Pod Logs

```shell
N/A
```

**Comment by totogtr** [comment]
I'm having the same issue, fixed it with a dedicated ClusterRole and ClusterRoleBinding

**Comment by jjacobelli** [comment]
Fixed by https://github.com/actions/actions-runner-controller/pull/2504
