### ISSUE TITLE
no such manifest: docker.io/summerwind/actions-runner:latest

### ISSUE THREAD

**Issue by bbednarek** [actions/actions-runner-controller#2235]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

v0.27.0

### Deployment Method

Helm

### cert-manager installation

not relevant 

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
not relevant
```

### To Reproduce

```markdown
run

docker manifest inspect summerwind/actions-runner:latest
```
```


### Describe the bug

exits with an error
```
no such manifest: docker.io/summerwind/actions-runner:latest
```

### Describe the expected behavior

inspects multi-arch docker manifest file

### Whole Controller Logs

```shell
not relevant
```

### Whole Runner Pod Logs

```shell
not relevant
```

### Additional Context

It used to work 3 weeks ago, because we have periodic job that stages `summerwind/actions-runner:latest` into our private registry

**Comment by Smirl** [comment]
Not a maintainer but there is a pinned issue saying latest has been remove. So I think it is by design and you should pin the image. 

There is an environment variable to disable auto update, which makes me think the runner try to update itself on start up by default. 

https://github.com/actions/actions-runner-controller/issues/2056

**Comment by bbednarek** [comment]
Thanks @Smirl for the heads up. I checked `ubuntu-22.04` and `ubuntu-20.04`  tags, but they don't have manifest either:
```
➜  ~ docker manifest inspect summerwind/actions-runner:ubuntu-22.04
no such manifest: docker.io/summerwind/actions-runner:ubuntu-22.04
➜  ~ docker manifest inspect summerwind/actions-runner:ubuntu-20.04
no such manifest: docker.io/summerwind/actions-runner:ubuntu-20.04
```

[EDIT]
I just found that image `ghcr.io` does have the manifest 
```
docker manifest inspect ghcr.io/actions/actions-runner-controller/actions-runner:ubuntu-20.04
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3042,
         "digest": "sha256:287baf2a10f0f09e718a1432040aadd3645e39167aa66ec1d37764be4ecd7e0f",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3041,
         "digest": "sha256:d9d4609e9d5201aa046f325e0c93a99c5a61862d4f006cf3e53bbb132a062f3a",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

Looks like there is some inconsistency between DockerHub and GitHub registries.

**Comment by mustafaStakater** [comment]
Github Registry was last updated 3 months ago , where as Docker Registry Updated 21 days ago.

**Comment by bbednarek** [comment]
Looks like 
```
docker manifest inspect summerwind/actions-runner:latest
```
works again
