### ISSUE TITLE
Latest actions-runner docker images are not available

### ISSUE THREAD

**Issue by krisztiankoszegi** [actions/actions-runner-controller#2270]
### What would you like added?

There is a new runner version available: `2.301.1`, but there is no actions-runner image with that version, only with the `2.299.1`.

Think the automation around [this](https://github.com/actions/actions-runner-controller/pull/2247) was made with version `2.301.1` in the [VERSION](https://github.com/actions/actions-runner-controller/blob/master/runner/VERSION) file instead of `2.299.1` and that's why the workflow is not triggering the build.  

### Why is this needed?

The current actions-runner image is 2 versions behind the latest.

### Additional context

The last 3 workflow runs didn't do anything: 
https://github.com/actions/actions-runner-controller/actions/workflows/update-runners.yaml

https://github.com/actions/actions-runner-controller/pkgs/container/actions-runner-controller%2Factions-runner

**Comment by Link-** [comment]
@krisztiankoszegi the links you provided are not where the runner images are published. These packages are still owned by the old organisation.

This is the correct URL: https://github.com/actions-runner-controller/actions-runner-controller/pkgs/container/actions-runner-controller%2Factions-runner

The remaining ones:
https://github.com/orgs/actions-runner-controller/packages
