### ISSUE TITLE
List labels in `kubectl get runnerdeployment`

### ISSUE THREAD

**Issue by cskinfill** [actions/actions-runner-controller#2308]
### What would you like added?

List the github action labels when someone runs `kubectl get runnerdeployment`

### Why is this needed?

Convenient to know which runnerdeployments have which labels.

### Additional context

`kubectl get runners` shows labels attached to specific runners, this would extend to `runnerdeployments` too.

**Comment by mumoshu** [comment]
Closing this as resolved via #2310. Thanks again for your feedback and contribution @cskinfill!
