### ISSUE TITLE
AutoscalingRunnerSet deployment doesn't work with github app returns 404 for actions.github.com

### ISSUE THREAD

**Issue by bainss** [actions/actions-runner-controller#2379]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

gha-runner-scale-set-controller:0.2.0

### Helm Chart Version

controller chart version 0.2.0

### CertManager Version

1.11.0

### Deployment Method

Helm

### cert-manager installation

Helm install used

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
githubConfigUrl defined
githubConfigSecret defined with githup appid,installation and private key
```

### To Reproduce

```markdown
helm install actions-runner-set-controller...
helm install actions-runner-scale-set ...
```

### Describe the bug

ERROR	AutoscalingRunnerSet	Failed to get runner scale set from Actions service	{"autoscalingrunnerset": "ci/actions-runner-dmn", "error": "404 - had issue communicating with Actions backend: Request returned status: 404 Not Found"}
261
github.com/actions/actions-runner-controller/controllers/actions%2egithub%2ecom.(*AutoscalingRunnerSetReconciler).createRunnerScaleSet
260
	github.com/actions/actions-runner-controller/controllers/actions.github.com/autoscalingrunnerset_controller.go:311
259
github.com/actions/actions-runner-controller/controllers/actions%2egithub%2ecom.(*AutoscalingRunnerSetReconciler).Reconcile
258
	github.com/actions/actions-runner-controller/controllers/actions.github.com/autoscalingrunnerset_controller.go:150
257
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
256
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122
255
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
254
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323
253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
252
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
251
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
250
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235

### Describe the expected behavior

should connect and runners acknowledged

### Whole Controller Logs

```shell
ERROR	AutoscalingRunnerSet	Failed to get runner scale set from Actions service	{"autoscalingrunnerset": "ci/actions-runner-dmn", "error": "404 - had issue communicating with Actions backend: Request returned status: 404 Not Found"}
261
github.com/actions/actions-runner-controller/controllers/actions%2egithub%2ecom.(*AutoscalingRunnerSetReconciler).createRunnerScaleSet
260
	github.com/actions/actions-runner-controller/controllers/actions.github.com/autoscalingrunnerset_controller.go:311
259
github.com/actions/actions-runner-controller/controllers/actions%2egithub%2ecom.(*AutoscalingRunnerSetReconciler).Reconcile
258
	github.com/actions/actions-runner-controller/controllers/actions.github.com/autoscalingrunnerset_controller.go:150
257
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
256
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122
255
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
254
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323
253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
252
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
251
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
250
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
```

### Whole Runner Pod Logs

```shell
ERROR	AutoscalingRunnerSet	Failed to get runner scale set from Actions service	{"autoscalingrunnerset": "ci/actions-runner-dmn", "error": "404 - had issue communicating with Actions backend: Request returned status: 404 Not Found"}
261
github.com/actions/actions-runner-controller/controllers/actions%2egithub%2ecom.(*AutoscalingRunnerSetReconciler).createRunnerScaleSet
260
	github.com/actions/actions-runner-controller/controllers/actions.github.com/autoscalingrunnerset_controller.go:311
259
github.com/actions/actions-runner-controller/controllers/actions%2egithub%2ecom.(*AutoscalingRunnerSetReconciler).Reconcile
258
	github.com/actions/actions-runner-controller/controllers/actions.github.com/autoscalingrunnerset_controller.go:150
257
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
256
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122
255
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
254
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323
253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
252
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
251
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
250
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
```

**Comment by Link-** [comment]
It works as expected, we have e2e tests that confirm it. Please upgrade to the latest version and make sure your firewalls / proxies are appropriately configured.

Closing this for now. If you reopen it please provide more information so that we can replicate the issue on our end.
