### ISSUE TITLE
Publish `actions-runner-controller` images to Github Container Registry

### ISSUE THREAD

**Issue by scruplelesswizard** [actions/actions-runner-controller#2385]
### What would you like added?

I would like all ARC-related container images to be published to a consistent container registry, specifically Github Container Registry (GHCR)

### Why is this needed?

Currently some images are being published to Docker Hub, while some are being published to GHCR. This inconsistency is confusing for some users, and requires additional overhead for users to maintain up-to-date images. 

### Additional context

Currently the `actions-runner-controller` image is not published to the `actions/` organization per [this query](https://github.com/orgs/actions/packages?tab=packages&q=actions-runner-controller)

**Comment by Link-** [comment]
@chaosaffe ALL actions-runner-controller images are published to GHCR. However, we made the decision to be as backward compatible as possible with existing setups and we didn't want to force anyone to update their helm repos.

- controller & runner images are here: https://github.com/orgs/actions-runner-controller/packages
- helm charts are here: https://github.com/actions-runner-controller/actions-runner-controller.github.io

This organisation is owned by GitHub.

The images you're seeing in the `actions` org are for the new version of actions-runner-controller which we have not yet been made available to the public.

**Comment by scruplelesswizard** [comment]
Thanks for the speedy reply and awesome information @Link-!
