### ISSUE TITLE
Add resources and nodeSelector options in values yaml of gha-runner-scale-set

### ISSUE THREAD

**Issue by Tal-E** [actions/actions-runner-controller#2486]
Hi, it would be great if you will add an option to add node selector and resources in the new gha-runner-scale-set helm chart

That way everybody can setup runners with a larger requests for CPU and memory

Currently, i do this locally by modifying the templates and installing the helm chart from locally, I think a lot of people would like to have it as an option in the values yaml it self, relatively a small and easy feature to add

**Comment by nikola-jokic** [comment]
Hey @tal-testim,

Are you referring to the change in the pod spec of ephemeral runners? If yes, you can modify the default pod [spec](https://github.com/actions/actions-runner-controller/blob/1a491cbfe5ec003fe14028574ba5f5675b04550b/charts/gha-runner-scale-set/values.yaml#L158) (which is of type `corev1.PodSpec`) of ephemeral runners to add nodeSelector or any other option you would like. :relaxed:

**Comment by nikola-jokic** [comment]
I will close this issue, and we can track it from the previous one: https://github.com/actions/actions-runner-controller/issues/2434
