### ISSUE TITLE
Using the token provided via Github Actions Settings

### ISSUE THREAD

**Issue by chuongnguyen5397** [actions/actions-runner-controller#2505]
### What would you like added?

I'm a Github user in a project. When I do the setup for self-hosted runner using this chart: https://artifacthub.io/packages/helm/actions-runner-controller/actions-runner-controller

The manager gave me the information from the Github Runner dashboard. Somethings like this: 

```
# Create a folder
$ mkdir actions-runner && cd actions-runner# Download the latest runner package
$ curl -o actions-runner-osx-arm64-2.303.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.303.0/actions-runner-osx-arm64-2.303.0.tar.gz# Optional: Validate the hash
$ echo "bbbac8011066b6cec93deb2365132b082b92287baaf34b5d9539e955ffe450ff  actions-runner-osx-arm64-2.303.0.tar.gz" | shasum -a 256 -c# Extract the installer
$ tar xzf ./actions-runner-osx-arm64-2.303.0.tar.gz

# Create the runner and start the configuration experience 
$ ./config.sh --url https://github.com/myProject --token <Token>
# Last step, run it! 
$ ./run.sh
```

How can I use it in the helm chart?

We only have `authSecret.github_app_id`, `authSecret.github_app_installation_id`, `authSecret.github_app_private_key`

### Why is this needed?

It can clear the confusing of newbie and also for people who is not admin

**Comment by Link-** [comment]
Please revisit our docs for this: https://github.com/actions/actions-runner-controller/blob/master/docs/authenticating-to-the-github-api.md
