### ISSUE TITLE
Customize gha autoscaling-listener pods

### ISSUE THREAD

**Issue by jjhidalgar** [actions/actions-runner-controller#2578]
### What would you like added?

Add support to modify the template that creates the autoscalinglisteners.actions.github.com listeners.

### Why is this needed?

Currently, using the new gha-runner-scale-set-controller you create 3 types of resources/pods:

* Helm chart: gha-runner-scale-set-controller
  * **A) Controller**
* autoscalinglisteners.actions.github.com CRD or Helm chart: gha-runner-scale-set
  * **B) gha-runner-scale-set (controller image in listener mode)**
* Job is triggered 
  * **C) autoscalingrunnersets.actions.github.com** is created by the listener

You can template A using the helm chart. You can set resources, node selectors, tolerations...

You can template C using the runner helm chart or configuring the CRD. You can completely configure your actual runners which is awesome

**You cannot configure the listener itself, which doesn't inherit either the controller's properties or the runner's properties. It will run without node selectors, resources....**. I've seen that you can configure the pullPolicy, but that's it, nothing else: https://github.com/actions/actions-runner-controller/pull/2477

Ideally It would be nice to template the listeners by configuring the runner CRD. But even inheriting a shared template from the controller would be better than current situation.

Some of us need to tag ALL pods in our clusters, either to use certain node groups, or for billing purposes, or for organizational purposes. But some people might even need to set custom images on internet-restricted clusters or other stuff.

**Comment by Link-** [comment]
Thank you @jaimehrubiks this is on our radar, but we haven't determined the optimal path forward for this. It's in our backlog.

**Comment by oWretch** [comment]
Another use case for customisation is the ability to mount a CSI secret into the listener pods so we can pull the token/app private key from Key Vault or another secret store.

**Comment by mikeclayton** [comment]
Another related motivation for being able customise the listener - Azure Kubernetes Service Policies might be configured to *require* resource limits on pods, but the controller doesn't apply any when it tries to create the listener, and you can't configure them for the listener in the Helm chart / ```values.yaml```...

#2612 - gha-runner-scale-set-controller error - "container <autoscaler> has no resource limits"

**Comment by booleanbetrayal** [comment]
We are also running into the fact that our listeners are over-provisioned in CPU. We have a `LimitRange` specification that also seeks to constrain other non-configurable pods, but even with that applied they request too much.

**Comment by Link-** [comment]
We already addressed this: https://github.com/actions/actions-runner-controller/pull/2758

**Comment by booleanbetrayal** [comment]
Somehow missed that value. Thanks @Link- !
