### ISSUE TITLE
Investigate why setup-python is failing on actions/runner image

### ISSUE THREAD

**Issue by Link-** [actions/actions-runner-controller#2610]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.4.0

### Helm Chart Version

0.4.0

### Deployment Method

Helm

### cert-manager installation

-

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
-
```

### To Reproduce

```markdown
Details: https://github.com/actions/actions-runner-controller/discussions/2174#discussioncomment-5961859
```

### Describe the bug

Action complains it didn't find a suitable version for the architecture:

```
 Version 3.11.3 was not found in the local cache
  Error: The version '3.11.3' with architecture 'x64' was not found for this operating system.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

### Describe the expected behavior

-

### Whole Controller Logs

```shell
-
```

### Whole Runner Pod Logs

```shell
-
```

**Comment by simpson** [comment]
You can see a lot of history here : https://github.com/actions/setup-python/issues/162

Also, Debian not supported
https://github.com/actions/setup-python/issues/401#issuecomment-1150563156

**Comment by onedr0p** [comment]
@Link- What is the point of using debian when it looks like Ubuntu is the most supported and compatible Linux variant for the runners?

**Comment by simpson** [comment]
> @Link- What is the point of using debian when it looks like Ubuntu is the most supported and compatible Linux variant for the runners?

+1 

Isn't this going to cause endless issues with the [GitHub Actions Marketplace](https://github.com/marketplace?type=actions) that are exclusively built for Ubuntu? This seems like a major miss for the Github ecosystem and community

**Comment by Link-** [comment]
We will switch to Ubuntu from Debian as of the next runner release (2.305.x+). For anyone who cannot wait until then, we highly recommend that you build and maintain your own runner images.

Our docs are quite comprehensive in this area: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller#about-the-runner-container-image

**Comment by simpson** [comment]
> We will switch to Ubuntu from Debian as of the next runner release (2.305.x+). For anyone who cannot wait until then, we highly recommend that you build and maintain your own runner images.
> 
> Our docs are quite comprehensive in this area: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller#about-the-runner-container-image

what is your timeline for that release?

**Comment by Link-** [comment]
@simpson No timeline for now.

**Comment by int128** [comment]
I noticed also [ruby/setup-ruby](https://github.com/ruby/setup-ruby) fails because it supports only Ubuntu.
I'm looking for the new release.

**Comment by simpson** [comment]
> I noticed also [ruby/setup-ruby](https://github.com/ruby/setup-ruby) fails because it supports only Ubuntu.
> I'm looking for the new release.

ya the current version is completely useless, hoping it doesn't take long for the next version to release 🤞

**Comment by Link-** [comment]
The new runner binaries and image will be release this week.

**Comment by Link-** [comment]
Switch from Debian to Ubuntu 22.04 https://github.com/actions/runner/pull/2651 - will come out with 2.305.0
