### ISSUE TITLE
actions-runner-controller-0.23.3 helm chart publish failure

### ISSUE THREAD

**Issue by brandongottesman-taulia** [actions/actions-runner-controller#2647]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.23.3

### Helm Chart Version

n/a

### CertManager Version

n/a

### Deployment Method

Helm

### cert-manager installation

n/a

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
n/a
```

### To Reproduce

```markdown
n/a
```

### Describe the bug

Missing helm chart for actions-runner-controller-0.23.3 due to failed helm publish step in CI job: https://github.com/actions/actions-runner-controller/actions/runs/4959241291/jobs/8873153299

### Describe the expected behavior

The helm chart for actions-runner-controller-0.23.3 should be published after a successful build of itself.

### Whole Controller Logs

```shell
n/a
```

### Whole Runner Pod Logs

```shell
n/a
```

### Additional Context

I'm mainly interested in deploying the helm chart containing the updates within [the actions-runner-controller-0.23.3 release](https://github.com/actions/actions-runner-controller/releases/tag/actions-runner-controller-0.23.3), specifically [the update allowing for `DOCKER_INSECURE_REGISTRY`](https://github.com/actions/actions-runner-controller/commit/80af7fc12580dbdf91f7327b6d5dd6e6e1ee4ec8).

**Comment by Link-** [comment]
The subsequent workflow runs succeeded. The helm charts are available. Closing this one, please re-open with more information if this assessment is incorrect.
