### ISSUE TITLE
Duplicating the roles+rolebinindgs when flags.watchSingleNamespace is set 

### ISSUE THREAD

**Issue by wherka-ama** [actions/actions-runner-controller#2668]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

gha-runner-scale-set-controller-0.4.0

### Helm Chart Version

0.4.0

### CertManager Version

N/A

### Deployment Method

Helm

### cert-manager installation

When testing this behaviour cert-manager is not relevant.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
This is around ARC v2, therefore these resource definitions are not applicable here as they are passed via values.yaml instead.
The context is not related to them either.
```

### To Reproduce

```markdown
1. Follow the setup as per with the exception of *flags.watchSingleNamespace*:
https://github.com/actions/actions-runner-controller/tree/master/docs/preview/gha-runner-scale-set-controller#setup
2. When invoking the helm upgrade/install add `--set=flags.watchSingleNamespace=<your namespace>` to the command
```

### Describe the bug

When the flags.watchSingleNamespace is set, the names of the roles and the rolebindings in `/home/wherka/workspace/gh/arc-sec/actions-runner-controller/charts/gha-runner-scale-set-controller/templates/manager_single_namespace_controller_role.yaml` and in `/home/wherka/workspace/gh/arc-sec/actions-runner-controller/charts/gha-runner-scale-set-controller/templates/manager_single_namespace_controller_role_binding.yaml` overlap these defined in: `charts/gha-runner-scale-set-controller/templates/manager_single_namespace_watch_role.yaml` and `charts/gha-runner-scale-set-controller/templates/manager_single_namespace_watch_role_binding.yaml` respectively.

This leads to the following error:
```
Error: roles.rbac.authorization.k8s.io "gha-runner-scale-set-controller-manager-single-namespace-role" already exists
helm.go:84: [debug] roles.rbac.authorization.k8s.io "gha-runner-scale-set-controller-manager-single-namespace-role" already exists
```

### Describe the expected behavior

The expected behaviour is a clean deployment of the chart with no errors.

### Whole Controller Logs

```shell
N/A
```

### Whole Runner Pod Logs

```shell
N/A
```

**Comment by wherka-ama** [comment]
@Link- : tagging you as per our conversation this morning. Thanks a lot for your effort!

**Comment by Link-** [comment]
@wherka-ama - this has been addressed here: https://github.com/actions/actions-runner-controller/pull/2617 

The PR will be merged once we run the E2E tests on it

**Comment by Link-** [comment]
Fix has been merged
