### ISSUE TITLE
ServiceAccount name for Runner Scale Set is too long and breaks Cillium CNI

### ISSUE THREAD

**Issue by robmaxwellirl** [actions/actions-runner-controller#2697]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.4.0

### Helm Chart Version

0.4.0

### CertManager Version

N/A

### Deployment Method

Helm

### cert-manager installation

Not used as using gha-runner-scale-set-controller which does not require it.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.github.com/v1alpha1
kind: EphemeralRunnerSet
metadata:
  annotations:
    actions.github.com/runner-group-name: my-org_self_hosted
  creationTimestamp: "2023-06-23T11:15:37Z"
  finalizers:
  - ephemeralrunner.actions.github.com/finalizer
  generateName: eksa-runner-set-
  generation: 3
  labels:
    actions.github.com/organization: my-org
    actions.github.com/scale-set-name: eksa-runner-set
    actions.github.com/scale-set-namespace: github-arc
    app.kubernetes.io/component: runner-set
    app.kubernetes.io/part-of: gha-runner-scale-set
    app.kubernetes.io/version: 0.4.0
    runner-spec-hash: 7d7955d559
  name: eksa-runner-set-z9dcl
  namespace: github-arc
  ownerReferences:
  - apiVersion: actions.github.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: AutoscalingRunnerSet
    name: eksa-runner-set
    uid: e5563e5e-fccf-4c4b-8320-edaad1ba1aff
  resourceVersion: "18509132"
  uid: 2b736a73-82ce-41f8-92a5-d46f8b528228
spec:
  ephemeralRunnerSpec:
    githubConfigSecret: github-access-token
    githubConfigUrl: https://github.com/udemy
    metadata: {}
    runnerScaleSetId: 2
    spec:
      containers:
      - command:
        - /home/runner/run.sh
        image: ghcr.io/actions/actions-runner:latest
        name: runner
        resources: {}
      serviceAccountName: eksa-runner-set-gha-runner-scale-set-no-permission-service-account
status:
  currentReplicas: 0
  pendingEphemeralRunners: 0
  runningEphemeralRunners: 0
```

### To Reproduce

```markdown
Create a kubernetes in a cluster which is using cillium as the container network interface.
Create a new deployment as above with the runner scale set a name longer than 11 characters installed via helm.

Trigger a job to run on this runner set and check the cillium logs on the node in which the runner container is trying to be created, it will be stuck in ContainerCreating status for a while.
```

### Describe the bug

Cillium has a name limit on the service account length similar to other constraints which should have been checked during the installation.

```
CiliumIdentity.cilium.io \"20516\" is invalid: metadata. labels: Invalid value: \"eksa-runner-set-gha-runner-scale-set-no-permission-service-account\": must be no more than 63 characters"
```

As a result of the service account name above, we can't start any runners.
Similar to how there's controls for the namespace and other resources, we should ideally place a reasource limit on the service account name also here?

https://github.com/actions/actions-runner-controller/blob/7ca3df360543a957d815cee3ebb1f681b2b66423/docs/preview/gha-runner-scale-set-controller/README.md#naming-error-name-must-have-up-to-characters

### Describe the expected behavior

Automatically generated service account name shouldn't be longer than 63 characters.

We should be able to define this ourselves, or shorten the service account name to abbreviate some of the name, as in "sa" instead of "-service-account"

This would allow not to run into these issues again.

### Whole Controller Logs

```shell
N/A
not an issue relating to the controller, but more around interaction with Cillium CNI within a cluster.
```

### Whole Runner Pod Logs

```shell
N/A
not an issue relating to the controller, but more around interaction with Cillium CNI within a cluster.
```

### Additional Context

I wasn't sure if this was something we could override ourselves, or look to shorten it's name in someplace. I was preparing a PR back to the repo to update how this value is defined within the helm chart during deployment, to abbreviate the name, but wanted to check before doing so.

**Comment by samip5** [comment]
This is currently blocking of using good ish names for the runners. :(

**Comment by budimanjojo** [comment]
This just affected me. I don't know why there's a `-service-account` prefix there, maybe it's added by `cillium`?
https://github.com/actions/actions-runner-controller/blob/0dadfc4d372a1cc689cfa7b05671d3a118595692/charts/gha-runner-scale-set/templates/_helpers.tpl#L60-L62

**Comment by Link-** [comment]
All of these are addressed in: https://github.com/actions/actions-runner-controller/pull/2706

**Comment by samip5** [comment]
> All of these are addressed in: https://github.com/actions/actions-runner-controller/pull/2706

Which unfortunately doesn't help us right now. :(
