### ISSUE TITLE
gha-runner-scale-set - pre-emptively scale runners based on new "min idle runners" setting

### ISSUE THREAD

**Issue by mikeclayton** [actions/actions-runner-controller#2707]
### What would you like added?

The new scaleset runners already support a ```minRunners``` and ```maxRunners``` setting in the gha-runner-scale-set helm charts:

https://github.com/actions/actions-runner-controller/blob/d134dee14b5ecd76ecbd2b3b2e1bc79fe3f4a95d/charts/gha-runner-scale-set/values.yaml#L39-L43

but it would be great if the runners also had a setting called something like ```minIdleRunners``` as well so that the runner group would scale up pre-emptively to ensure there were idle runners already available when a new workflow run arrives in the queue.

### Why is this needed?

Sometimes, scaling up can be a slow operation and waiting to do it on-demand when a new workflow is triggered could mean the workflow is delayed by several minutes while the scale-up event is processed - for example if a new node needs to be dynamically provisioned and added to the kubernetes cluster for the runner pod to be scheduled onto.

Scaling up pre-emptively to ensure there are always a predefined number of idle runners would mean workflows could start sooner.

For example, if the *current* gha-runner-scale-set ```values.yaml``` is configured as follows:

```
maxRunners: 10
minRunners: 2
```

... then the first two workflows that arrive will be immediately assigned to the two idle runners (lets assume they both take about 10-15 minutes to complete) . There are now 2 runners but they're both busy, so if a third workflow is triggered 5 minutes later it will need to wait for another runner pod to be provisioned and *that* could also require a new node to be dynamically provisioned and added to the kubernetes cluster, which might take several minutes.

If there were a ```minIdleRunners``` setting, the scale-up event would be triggered as soon as the two initial workflows were allocated to runners and became busy, so that the scale up to create 2 more *idle* runners would have already competed by the time the third workflow is triggered and a runner would be available to start the third workflow immediately.

### Additional context

**Note:** The new setting could potentially conflict with the existing ```minRunners``` and ```maxRunners``` in some cases - e.g.

```
maxRunners: 10
minRunners: 2
minIdleRunners: 100
```
or
```
maxRunners: 10
minRunners: 2
minIdleRunners: 0
```
or if there are, say, already 9 "busy" runners there could only be one additional idle runner provisioned.

The ```minIdleRunners``` setting would be "advisory" and would yield to the ```minRunners```and ```maxRunners``` settings when a conflict arises.

**Comment by samchoraria** [comment]
👍  `minIdleRunners` would be a really useful addition for our deployment also.

Just a related observation; regarding the job queue draining [example](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#example-jobs-queue-draining) in the current docs. 

We've noticed setting `minRunners:` to an `int` > 0 reduces the numbers of *idle* runners, e.g. changing configuration from `minRunners:10` > `minRunners:5` and redeploying will drain/terminate 5 *idle* runners. 

However changing configuration from `minRunners:5` > `minRunners:0` (or commenting out the setting) and redeploying appears to disable the setting without actually draining/terminating any *idle* runners, i.e. 5 *idle* runners still remain.

It would be useful for maintenance purposes to fully drain *idle* runners, when setting `minRunners:0`.
