### ISSUE TITLE
Controllers panic after update to EKS 1.27

### ISSUE THREAD

**Issue by baudlord** [actions/actions-runner-controller#2709]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.4

### Helm Chart Version

0.23.3

### CertManager Version

1.12.2

### Deployment Method

Helm

### cert-manager installation

Cert-Manager is working properly.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
Not an issue related to RunnerDeployment / RunnerSet.
```

### To Reproduce

```markdown
1. Update to EKS 1.27
2. Controllers panic.
```

### Describe the bug

Controller panics. Likely related to the latest client-go and controller-runtime updates for 1.27.

### Describe the expected behavior

Controller works normally.

### Whole Controller Logs

```shell
https://gist.github.com/baudlord/d0e7755d44ffcc5a36c42d69b9ca256e
```

### Whole Runner Pod Logs

```shell
Not an issue related to RunnerDeployment / RunnerSet.
```

### Additional Context

```shell
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"archive", BuildDate:"2023-06-15T08:14:06Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.2-eks-c12679a", GitCommit:"002c6bc4e142b1f48b9405140e559194a094dcff", GitTreeState:"clean", BuildDate:"2023-05-22T20:23:13Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jstewart612** [comment]
@baudlord how was this solved?  We have this problem right now.

**Comment by baudlord** [comment]
EKS 1.27.3 fixed this for me.
