### ISSUE TITLE
When the Runner terminates, refer to why the Runner terminated and suppress the addition of EphemeralRunner to the failure.

### ISSUE THREAD

**Issue by kahirokunn** [actions/actions-runner-controller#2722]
### What would you like added?

If the runner starts successfully, waits for a job successfully, and exits when the job is not being processed, how about not adding it to the failure list?

### Why is this needed?

RUNNER was started on a SPOT instance with minRunners at 1.
Each time the spot instance terminates, the runner naturally terminates as well.
When runner terminates, a failure is added to EphemeralRunner.
Because of this, I cannot make the runner reside on the spot instance.

### Additional context

https://github.com/actions/actions-runner-controller/issues/2721

**Comment by nikola-jokic** [comment]
Let's close this issue since it is decided not to make it work on spot instances, at least for now :relaxed:
