### ISSUE TITLE
Autoscaling Runner Scale Sets - dind fails "Cannot connect to the Docker daemon"

### ISSUE THREAD

**Issue by Lifeismana** [actions/actions-runner-controller#2746]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

gha-runner-scale-set-controller-0.4.0

### Helm Chart Version

0.4.0

### Deployment Method

Helm

### cert-manager installation

Autoscaling Runner Scale doesn't require cert-manager

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
not relevant
```

### To Reproduce

```markdown
ARC was installed following the doc with no modification

here's a redacted version of the workflow that i'm running

env:
  IMAGE_NAME: github/test

jobs:
  build:
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.1.1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
```

### Describe the bug

action fails with 
`ERROR: failed to initialize builder builder-c898e407-0313-48a8-93fd-3c5e569f31e6 (builder-c898e407-0313-48a8-93fd-3c5e569f31e60): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
when setting up  `docker/setup-buildx-action`

this cluster doesn't experience this problem when using the old scaling way

### Describe the expected behavior

action should be able to use docker in docker

### Whole Controller Logs

```shell
https://gist.github.com/Lifeismana/d39f07fb63c5639d2ae348a5cdee9eeb#file-controller-log
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/Lifeismana/d39f07fb63c5639d2ae348a5cdee9eeb#file-runner-log
```

### Additional Context

The cluster ARC is running on is using k3s but I've also tried using kind & minikube (as mentionned in the doc) but i was getting the same error

**Comment by Lifeismana** [comment]
Seems like i missed the fact that dind, isn't enabled by default in this mode, still after enabling it, i'm still getting the same error

**Comment by iniinikoski** [comment]
Hi!

I just enabled dind for our scale-sets, and got things working just by that.

Our Actions-workflow looks like this: https://gist.github.com/iniinikoski/3a55a6203c1ba28b0eaeef93d19bde98

Which does look a bit different from yours... I hope / maybe that helps you too...

**Comment by iiro** [comment]
And, enabled dind simply by:

> containerMode:
      type: "dind"

**Comment by Lifeismana** [comment]
Thank you both, 
these were indeed my 2 mistakes, not enabling dind & not using the docker context command (i think i'm blind for this one because the error message does mention that command...)
Now my workflow is working correctly, Thanks again!
