### ISSUE TITLE
Be able to set pod labels 

### ISSUE THREAD

**Issue by perrness** [actions/actions-runner-controller#2753]
### What would you like added?

When installing **gha-runner-scale-set-controller** with the helm chart, have a `podlabels` field in the **values.yaml**, that can be used to set labels for the pods. In a similar way as `podannotations`.

### Why is this needed?

We have policies in place that require some specific pod labels in our clusters, so it would be nice to have this option. This template value is also available in the "old"  actions-runner-controller which we are migrating from.

### Additional context

Something like this https://github.com/actions/actions-runner-controller/blob/5271f316e6e068f0daf4b202d7c8b9f21301fbd1/charts/actions-runner-controller/values.yaml#L88

**Comment by perrness** [comment]
The listener pod and runner pods also should be configurable with pod labels.

**Comment by nikola-jokic** [comment]
Hey @perrness,

You can set those labels by modifying the `template.spec.metadata.labels` field for the runners (https://github.com/actions/actions-runner-controller/blob/dcb64f0b9e889f4751bf257f2a37632ce10a3e10/charts/gha-runner-scale-set/templates/autoscalingrunnerset.yaml#L93)

The pod spec template is exposed for that reason, so you can modify fields associated with the metadata as well.

For the listener, there is an [ongoing work](https://github.com/actions/actions-runner-controller/pull/2758) to provide a customizable template where you can apply labels to the listener pod itself

**Comment by perrness** [comment]
I see! Thank you for the tip and update on the issue.

**Comment by nikola-jokic** [comment]
Closing this issue since the listener labels are part of the 0.6.0 :relaxed:
