### ISSUE TITLE
Outdated latest tag on ghcr.io/actions/actions-runner-controller/actions-runner

### ISSUE THREAD

**Issue by YoranSys** [actions/actions-runner-controller#2761]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

NA

### Helm Chart Version

NA

### CertManager Version

NA

### Deployment Method

Helm

### cert-manager installation

NA

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
NA
```

### To Reproduce

```markdown
NA
```

### Describe the bug

The latest tag on ghcr.io/actions/actions-runner-controller/actions-runner is v2.299.1-ubuntu-20.04-aa6dab5, while on Docker Hub the latest tag is v2.306.0-ubuntu-20.04-e0a7e14.

### Describe the expected behavior

The latest tag on ghcr.io/actions/actions-runner-controller/actions-runner should reflect the latest version available on Docker Hub, which is currently v2.306.0-ubuntu-20.04-e0a7e14.

### Whole Controller Logs

```shell
NA
```

### Whole Runner Pod Logs

```shell
NA
```

### Additional Context

 Having the latest version available on ghcr.io allows users to access the most up-to-date features and bug fixes without using docker hub.

**Comment by nikola-jokic** [comment]
Hey @YoranSys 

The community runner images are located at https://github.com/orgs/actions-runner-controller/packages. The image you are referring to is an artifact left from the migration, and have been deleted now. :relaxed: 
The officially supported image is located [here](https://github.com/actions/runner/pkgs/container/actions-runner).

**Comment by phclark** [comment]
It's not okay to just remove an image, people..
