### ISSUE TITLE
Regional Failover Capabilities for GitHub Actions Runner Controller

### ISSUE THREAD

**Issue by chachank** [actions/actions-runner-controller#2764]
### What would you like added?
I would like to request the implementation of regional failover capabilities for the GitHub Actions Runner.

### Why is this needed?

To ensure high availability and disaster recovery for our development workflows on GitHub Actions, implementing regional failover for the Runner is essential. Should a region fail, the failover system needs to transparently shift the workload to another region, reducing potential downtime to a minimum and sustaining workflow continuity. We aim to put this into action on Azure AKS, allowing regional failover to safeguard our workflows from region-wide failures. The failover will provide resilience by rerouting builds and jobs to available Runners in an alternate region during outages. This will help minimize disruption to developers and maintain productivity. Implementing robust failover will provide stability during regional outages on Azure AKS.

### Additional context

As our organization relies heavily on GitHub Actions Runner for our CI/CD processes for deploying critical applications, ensuring regional failover capabilities is of paramount importance to us. We are aware that this feature may involve architectural changes and synchronization mechanisms across different regions. However, we firmly believe that it will significantly enhance the reliability and resilience of the GitHub Actions Runner in critical scenarios.

**Comment by nikola-jokic** [comment]
Hey @chachank,

Are you referring to the `actions.summerwind.net`, or the `actions.github.com` API group?

**Comment by chachank** [comment]
Hi @nikola-jokic,

I was referring to `actions.github.com` API group.

**Comment by nikola-jokic** [comment]
Thank you for clarification!

ARC can be deployed in a high availability (active-active) configuration. Assuming you have 2 distinct Kubernetes clusters, A and B deployed in separate regions, you can deploy ARC in both clusters and configure runner scale sets to use the same `runnerScaleSetName` as long as they're assigned to 2 distinct runner groups at the organization or enterprise level.

The runner scale set names are unique within the runner group they belong to. As an example, you can have 2 runner scale sets with the same name `arc-runner-set` as long as they belong to `runner-group-A` and `runner-group-B` respectively.

Assuming both runner scale sets are online, jobs assigned to them will be distributed arbitrarily (assignment race). You cannot configure the job assignment algorithm. If one of the clusters goes down, the runner scale set in the other cluster will continue to acquire jobs normally without any intervention or configuration change.

**Comment by nikola-jokic** [comment]
Closing this issue since it is documented [here](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#high-availability-and-automatic-failover)
