### ISSUE TITLE
Unable to override dind container via values

### ISSUE THREAD

**Issue by ldaneliukas** [actions/actions-runner-controller#2765]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.23.3

### Helm Chart Version

0.4.0

### Deployment Method

Helm

### To Reproduce

```markdown
1. Install the scale set operator
2. Install oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
3. Provide the follow values as per README and GitHub [documentation](https://docs.github.com/en/enterprise-server@3.9/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#using-docker-in-docker-mode):

# Container modifications
template:
  spec:
    containers:
    - name: runner
      image: "custom.registry.com/actions/actions-runner:latest"
      imagePullPolicy: Always
      command: ["/home/runner/run.sh"]
    - name: dind
      image: "custom.registry.com/docker:dind"
```

### Describe the bug

Supplying a values file with `template.spec` to override default configuration does not work for the `dind` container. For example, using the values file to override container registries for the runner and dind will result in the image for the runner being modified, but the image for `dind` not.

This is likely due to the fact that there is no logic implementing this feature [here](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/_helpers.tpl#L89:L100), even though it is documented as existing [here](https://docs.github.com/en/enterprise-server@3.9/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#using-docker-in-docker-mode) - `The template.spec will be updated to the following default configuration. You can override any of these values to customize your setup.`

This prevents the use of `dind` mode in situations where admission webhook are used to force custom docker registries.

```
2023-07-24T08:04:41Z	ERROR	Reconciler error	{"controller": "ephemeral-runner-controller", "controllerGroup": "actions.github.com", "controllerKind": "EphemeralRunner", "EphemeralRunner": {"name":"arc-runners-lj2pt-runner-4h49r","namespace":"github-actions"}, "namespace": "github-actions", "name": "arc-runners-lj2pt-runner-4h49r", "reconcileID": "0d1f694a-28fc-486c-9c36-061a499489e0", "error": "admission webhook \"check-webhook.kube-system.svc\" denied the request: Image container.Image: docker:dind"}
```

This can be verified by inspecting the `autoscalingrunnersets.actions.github.com` resource, e.g. `k describe autoscalingrunnersets.actions.github.com arc-runners` - shows that the container for `dind` is still `docker:dind`.

### Describe the expected behavior

The container image for `dind` should have been updated by modifying the values for `template.spec`.

### Whole Controller Logs

```shell
2023-07-24T08:10:09Z	INFO	EphemeralRunner	Creating new EphemeralRunner pod.	{"ephemeralrunner": "github-actions/arc-runners-lj2pt-runner-4h49r"}
2023-07-24T08:10:09Z	INFO	EphemeralRunner	Creating new pod for ephemeral runner	{"ephemeralrunner": "github-actions/arc-runners-lj2pt-runner-4h49r"}
2023-07-24T08:10:09Z	INFO	EphemeralRunner	Created new pod spec for ephemeral runner	{"ephemeralrunner": "github-actions/arc-runners-lj2pt-runner-4h49r"}
2023-07-24T08:10:09Z	ERROR	EphemeralRunner	Failed to create pod resource for ephemeral runner.	{"ephemeralrunner": "github-actions/arc-runners-lj2pt-runner-4h49r", "error": "admission webhook \"check-webhook.kube-system.svc\" denied the request: Image container.Image: docker:dind"}
github.com/actions/actions-runner-controller/controllers/actions%2egithub%2ecom.(*EphemeralRunnerReconciler).createPod
	github.com/actions/actions-runner-controller/controllers/actions.github.com/ephemeralrunner_controller.go:618
github.com/actions/actions-runner-controller/controllers/actions%2egithub%2ecom.(*EphemeralRunnerReconciler).Reconcile
	github.com/actions/actions-runner-controller/controllers/actions.github.com/ephemeralrunner_controller.go:203
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
2023-07-24T08:10:09Z	ERROR	Reconciler error	{"controller": "ephemeral-runner-controller", "controllerGroup": "actions.github.com", "controllerKind": "EphemeralRunner", "EphemeralRunner": {"name":"arc-runners-lj2pt-runner-4h49r","namespace":"github-actions"}, "namespace": "github-actions", "name": "arc-runners-lj2pt-runner-4h49r", "reconcileID": "a074b8f2-c418-40d2-a984-ebf71f200228", "error": "admission webhook \"check-webhook.kube-system.svc\" denied the request: Image container.Image: docker:dind"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
```

### Whole Runner Pod Logs

```shell
N/A - does not start.
```

**Comment by nikola-jokic** [comment]
Hey @LDaneliukas,

In case dind should be customized, the `containerMode` should be empty and you can provide dind container inside the template. I have created a PR that should document this approach. Thank you for raising this issue!

**Comment by ldaneliukas** [comment]
Hey! The last time i supplied the full spec template something went wrong, but I'll need to try that out again and get back to you. I suppose it should work, but would be a pain to maintain and keep up to date with the chart instead of having that nice abstraction.

**Comment by nikola-jokic** [comment]
In case of simple modifications, like modifying the image, I would agree 100% ☺️ 
But once you get to more complicated situations, then merging two specs can be unintuitive (Merging volumes, etc) and also, error-prone. You can leverage helms `--dry-run` to see exactly what is going to be applied in case of `containerMode: dind`, and then just copy the spec for the `dind` container, exclude containerMode and modify fields that you'd like
Then the only thing you need to maintain is the values.yaml file

**Comment by hamishforbes** [comment]
> In case of simple modifications, like modifying the image, I would agree 100% ☺️ But once you get to more complicated situations, then merging two specs can be unintuitive (Merging volumes, etc) and also, error-prone. You can leverage helms `--dry-run` to see exactly what is going to be applied in case of `containerMode: dind`, and then just copy the spec for the `dind` container, exclude containerMode and modify fields that you'd like Then the only thing you need to maintain is the values.yaml file

I'm struggling with similar issues here just trying to get very basic stuff customised (e.g. using public ECR dind image instead of docker hub, setting resource requests/limits etc).

Given the generated AutoscalingRunnerSet resources is reconciled by the controller running actual proper code (as opposed to a helm template)
Can we do all this complex merging logic etc in the controller?
There are known hard requirements (like setting the command, env vars, volumes) for the runner to actually function.
The controller should be aware of these and make sure they exist rather than trying to awkwardly shoe-horn them in with Helm

**Comment by nikola-jokic** [comment]
Hey @hamishforbes,

Not really, without changing the interface. Helm is used as a mechanism to create kubernetes objects from templates. We support helm charts that we publish, but one can achieve this using the kustomize or plain yaml, as long as the definition matches the expected one.

In this case, helm is used to create a spec applied to the kube-apiserver. Once there, the controller picks up the object and reconciles on it. Merging the spec would need to change the AutoscalingRunnerSet CRD. We would need to pass down the object as a spec field, and then do a merge. It would defeat the original purpose of the controller as it is basically a reconcile loop trying to bring the cluster state to your desired state.

The object you applied to the API server should express your desired state. Mixing these two responsibilities would also increase the complexity of the controller, introducing another responsibility to it.

Also, it would be unclear what the template looks like because it would introduce another sidecar container. That is one of the reasons why we choose to expose pod template spec, instead of picking the fields. Pod template describes your runner pod. The `containerMode` field is only provided as an out-of-box solution but can be completely ignored in case your runner pod needs more customization

**Comment by hamishforbes** [comment]
> Not really, without changing the interface. 

That is what I'm suggesting.

>Helm is used as a mechanism to create kubernetes objects from templates. We support helm charts that we publish, but one can achieve this using the kustomize or plain yaml, as long as the definition matches the expected one.

Yeah, I'm familiar with how helm works
 
> In this case, helm is used to create a spec applied to the kube-apiserver. Once there, the controller picks up the object and reconciles on it. Merging the spec would need to change the AutoscalingRunnerSet CRD. We would need to pass down the object as a spec field, and then do a merge. It would defeat the original purpose of the controller as it is basically a reconcile loop trying to bring the cluster state to your desired state.

I disagree, fundamentally the *purpose* of the controller is to abstract complexity away from the user and into code.
That's the point of a CRD and a controller right? To avoid the user having to use lower level tools/objects (like `Pod`) to solve their problem.

> The object you applied to the API server should express your desired state. Mixing these two responsibilities would also increase the complexity of the controller, introducing another responsibility to it.

Yes and my desired state is 'An autoscaling runner pool with minor customisations' not 'The entire spec for a working implementation of a runner'

> Also, it would be unclear what the template looks like because it would introduce another sidecar container. That is one of the reasons why we choose to expose pod template spec, instead of picking the fields. Pod template describes your runner pod. The `containerMode` field is only provided as an out-of-box solution but can be completely ignored in case your runner pod needs more customization

That's fine, but if you want to go that way I think you need to improve the documentation on how to actually configure the pod spec to work.

I still think you're pushing complexity down to the end-user which should be in the controller. 
There are a number of issues from users trying to use the new system and failing at the first hurdle, which is not a great experience.
