### ISSUE TITLE
Unable to pull from ghcr

### ISSUE THREAD

**Issue by amit-disc** [actions/actions-runner-controller#2766]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.20.0

### Helm Chart Version

0.20.0

### Deployment Method

Helm

### cert-manager installation

Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
Not relevant
```

### To Reproduce

```markdown
ghcr.io/actions/actions-runner-controller/actions-runner:v2.299.1-ubuntu-20.04-aa6dab5 ImagePullBackOff error starting from today
```

### Describe the bug

Unable to pull from ghcr.io/actions/actions-runner-controller/actions-runner:v2.299.1-ubuntu-20.04-aa6dab5 . It was working yesterday.

### Describe the expected behavior

Able to pull ghcr.io/actions/actions-runner-controller/actions-runner:v2.299.1-ubuntu-20.04-aa6dab5

### Whole Controller Logs

```shell
NA
```

### Whole Runner Pod Logs

```shell
NA
```

**Comment by nikola-jokic** [comment]
Hey @amit-disc,

As mentioned in [this issue](https://github.com/actions/actions-runner-controller/issues/2761), the image you are using is a leftover from the migration. The correct image can be found [here](https://github.com/actions-runner-controller/actions-runner-controller/pkgs/container/actions-runner-controller%2Factions-runner).

I will leave this issue open for now for visibility :relaxed:

**Comment by amit-disc** [comment]
> Hey @amit-disc,
> 
> As mentioned in [this issue](https://github.com/actions/actions-runner-controller/issues/2761), the image you are using is a leftover from the migration. The correct image can be found [here](https://github.com/actions-runner-controller/actions-runner-controller/pkgs/container/actions-runner-controller%2Factions-runner).
> 
> I will leave this issue open for now for visibility ☺️

@nikola-jokic Thank you so much :) Do you know where the migration was announced? or was it something internal?

**Comment by nikola-jokic** [comment]
Hey, of course, here is the issue that tracked repository transfer: https://github.com/actions/actions-runner-controller/issues/2089
During that time, the images were also reflected under actions, but they belong to the `actions-runner-controller` org :relaxed: We are sorry this caused you trouble
