### ISSUE TITLE
Workflow job queue metric not working

### ISSUE THREAD

**Issue by alexshevch-wise** [actions/actions-runner-controller#2819]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

v0.27.4-f798cdd

### Deployment Method

Helm

### cert-manager installation

yes we confirm certmanager installation, there are no issues with the cert manager.

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
not relevant
```

### To Reproduce

```markdown
1. deploy the latest version of the controller and runners
2. Run any workflow build with the runner
3. Get metrics from actions-runner-controller-actions-metrics-server-xxx
4. `github_workflow_job_queue_duration_seconds` metric is expected to be exposed, but it is not.
```

### Describe the bug

Prometheus is not exporting any `NewHistogramVec` metrics after upgrade from 0.27.0 to 0.27.4
For example: `github_workflow_job_queue_duration_seconds` or `github_workflow_job_run_duration_seconds`
Other types of metrics are not affected

Looks like it was introduced by the metricLabels []string change 
here: https://github.com/actions/actions-runner-controller/pull/2225
or here: https://github.com/actions/actions-runner-controller/pull/2549

A workaround to fix the issue is to revert back to only metrics server pod to a previous version of the image `summerwind/actions-runner-controller:v0.27.0-e1fcd63`

### Describe the expected behavior

`github_workflow_job_queue_duration_seconds` and`github_workflow_job_run_duration_seconds` are exposed by the running metrics server

### Whole Controller Logs

```shell
not relevant
```

### Whole Runner Pod Logs

```shell
not relevant
```

**Comment by jespada** [comment]
@alexshevch-wise  what's the fix for this? I've experience the same issue

**Comment by alexshevch-wise** [comment]
We digged deeper into the code and noticed that the secret name has changed for the metrics server. Somehow during the upgrade between versions the secret rename got lost. Once we corrected the helm parameters the deployment picked up the secret and authorised in GH to fetch this metric.
If you are having the same issue, you should see a warning msg in the metrics server logs about this authentication failure
