### ISSUE TITLE
cached docker volume in gha-runner-scale-set

### ISSUE THREAD

**Issue by JohnYoungers** [actions/actions-runner-controller#2940]
### What would you like added?

In the existing implementation of `actions-runner-controller`, you could optionally come up with a way to cache docker images by customizing the `/var/lib/docker` path as described here: https://github.com/actions/actions-runner-controller/blob/master/docs/using-custom-volumes.md

Is there a recommended approach for doing something similar in `gha-runner-scale-set`?

### Why is this needed?

For workflows that use containers (e.g. `services`), run time can be greatly improved/made more consistent if images already exist locally

### Additional context

In the helm chart, you can override the container configuration of the runner by including values in an `template.spec.containers[]` object where `name: "runner"`.  If this docker image caching were an option, I think there would need to be similar logic applied to the `dind` container as well: https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/_helpers.tpl#L98

**Comment by JohnYoungers** [comment]
It sounds like the recommended approach would be to unset `containerMode: { type: "dind" }` and then manually configure the containers based on some of the other issues/documentation.

I'll likely need to do so to remove the verbose piece from the init container (`["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]`) since that's blowing up our logs, but I had a question regarding the container in general:  if it's purpose is only to copy over files to the `dind` container, is there any reason that couldn't be baked into another image (e.g. `ghcr.io/actions/actions-runner-dind:latest` based on `docker:dind`)?

```Dockerfile
FROM docker:dind

COPY --from=ghcr.io/actions/actions-runner:latest /home/runner/externals/. /home/runner/tmpDir/
```

**Comment by Link-** [comment]
> It sounds like the recommended approach would be to unset containerMode: { type: "dind" } and then manually configure the containers based on some of the other issues/documentation.

100%

> if it's purpose is only to copy over files to the dind container, is there any reason that couldn't be baked into another image (e.g. ghcr.io/actions/actions-runner-dind:latest based on docker:dind)?

@JohnYoungers we want to reduce the number of container images we publish

**Comment by omri-shilton** [comment]
We are also in need for the exact same feature.


> It sounds like the recommended approach would be to unset `containerMode: { type: "dind" }` and then manually configure the containers based on some of the other issues/documentation.

I dont quite understand what you meant by unsetting that mode. there are only two modes for the gha-runner-scale-set. dind and kubernetes. care to explain a bit further on how that could help with cached images?

From my experience with the old dynamic PVs and runnerset to control cache of docker images, we really didn't have a good experience with this feature. You can also see many issues on the subject that people aren't very happy with it.
So a better solution would be best.

**Comment by JohnYoungers** [comment]
> I dont quite understand what you meant by unsetting that mode. there are only two modes for the gha-runner-scale-set. dind and kubernetes. care to explain a bit further on how that could help with cached images?

If either mode is active, the helm chart will include settings on your behalf: by unsetting, you would manually specify what the containers look like.

@Link- would it be possible to shed some insight on what's relying on those files from the initContainer?  I've updated my helm chart values with the following, using the vanilla dind image: it seems to be working for my use cases, as well as using cached images from the `var-lib-docker` volume as was my original goal.  I'm just concerned with what issues I could potentially run into in the future

Here's the typescript code which generates the yaml for the helm chart:

```ts
const runnerContainer = {
  name: "runner",
  image: `my-custom-image:latest`,
  env: [] as any[],
  volumeMounts: [] as any[],
  resources: {
    requests: {
      cpu: runner.cpu,
      memory: runner.memory,
    },
  },
};
const containers: any[] = [runnerContainer];
const volumes: any[] = [];

if (runner.enableDocker) {
  runnerContainer.env.push({ name: "RUNNER_WAIT_FOR_DOCKER_IN_SECONDS", value: "60" });
  runnerContainer.env.push({ name: "DOCKER_HOST", value: "unix:///run/docker/docker.sock" });
  runnerContainer.volumeMounts.push({ name: "dind-sock", mountPath: "/run/docker", readOnly: true });

  containers.push({
    name: "dind",
    image: "docker:dind",
    args: ["dockerd", "--host=unix:///run/docker/docker.sock", "--group=$(DOCKER_GROUP_GID)"],
    securityContext: { privileged: true },
    env: [{ name: "DOCKER_GROUP_GID", value: "123" }],
    volumeMounts: [
      { name: "dind-sock", mountPath: "/run/docker" },
      { name: "var-lib-docker", mountPath: "/var/lib/docker" },
    ],
  });

  volumes.push({ name: "dind-sock", emptyDir: {} });
  volumes.push({
    name: "var-lib-docker",
    ephemeral: {
      volumeClaimTemplate: {
        spec: {
          accessModes: ["ReadWriteOnce"],
          resources: { requests: { storage: "20Gi" } },
          storageClassName: "gp3",
          dataSource: {
            name: `docker-snapshot-12345`,
            kind: "VolumeSnapshot",
            apiGroup: "snapshot.storage.k8s.io",
          },
        },
      },
    },
  });
}
```

**Comment by Link-** [comment]
> @Link- would it be possible to shed some insight on what's relying on those files from the initContainer?

@JohnYoungers these contain the node runtime and other dependencies needed for the functioning of the runner. You'll need them in both containers.

https://github.com/actions/runner/blob/f57ecd8e3c618e1723cdf02565e5f4da188776a4/src/Misc/externals.sh#L36

**Comment by Link-** [comment]
I'm converting this to a discussion
