### ISSUE TITLE
Improve troubleshooting AutoscalingRunnerSet pods and reason for termination

### ISSUE THREAD

**Issue by wojciechka** [actions/actions-runner-controller#2943]
### What would you like added?

When running `gha-runner-scale-set-controller` and using `AutoscalingRunnerSet`, sometimes the ephemeral pods get killed as they reach resource limits.

The pod gets removed, making it hard to understand reason for the termination (memory limit, ephemeral-storage limit, other reason).

The controller could log details for any pod/job that did finish successfully.

If in the future the controller exposes metrics, the data could also be provided in this way for convenient monitoring.

### Why is this needed?

It's hard to troubleshoot and/or monitor issues with runners without visibility into failures.

Looked into checking data using metrics (`kube-prometheus-stack`), CPU/memory usage is there, but ephemeral-storage is not ( kubernetes/kubernetes#69507 ). Metrics don't store reason for termination or anything meaningful.

Checked and `gha-runner-scale-set-controller` does not expose custom metrics that could expose any data related to this.

**Comment by Link-** [comment]
This is an interesting problem to solve @nikola-jokic

**Comment by wojciechka** [comment]
Ran into a related issue today. Using a specific image of the runner, the runner stopped working today as the image became deprecated. This on its own is fine and understandable, but it was not possible to troubleshoot it anywhere.

I checked the logs for the controller and listener and did not find any information. By trial and error I was able to delete `ephemeralrunner` to trigger a new runner to be run and `kubectl logs -f` to get an error like:

```
[RUNNER 2023-10-19 08:47:45Z ERR  Listener] GitHub.DistributedTask.WebApi.AccessDeniedException: Runner version v2.308.0 is deprecated and cannot receive messages.
```

It'd be good if the controller or listener would somehow get notified about errors like this one or if key issues like this would be stored in events for `EphemeralRunner`, so the data is easier to access.

This is somewhat related, but I can also open a separate issue for this - technically both are about having a way to troubleshoot past runs of a pod that did not succeed to start or finish running a job. Please let me know if this is something I should do.

ps. Yes, the information about deprecation is in the results of past GitHub actions run, but often the teams managing the infrastructure for runners may not be the ones looking at results from the runners.

**Comment by nikola-jokic** [comment]
Hey @wojciechka,

I agree, troubleshooting failing ephemeral runners is not great... I would love to avoid pulling the logs from the ephemeral runner and logging the output inside the controller. The reason is that controller can manage a lot of runners and the runner can also produce a large log.

However, we can potentially patch the status with the runner log once we mark the `EphemeralRunner` resource as failed. The log would be the log of the latest restart. That will somewhat increase the data stored in the etcd at least temporarily, but it would provide a good starting point for troubleshooting at least. That may be one of the solutions, at least for now, and we can improve on that later.

What do you think, @Link-?

**Comment by MPV** [comment]
> Ran into a related issue today. Using a specific image of the runner, the runner stopped working today as the image became deprecated. This on its own is fine and understandable, but it was not possible to troubleshoot it anywhere.
> 
> 
> 
> I checked the logs for the controller and listener and did not find any information. By trial and error I was able to delete `ephemeralrunner` to trigger a new runner to be run and `kubectl logs -f` to get an error like:
> 
> 
> 
> ```
> 
> [RUNNER 2023-10-19 08:47:45Z ERR  Listener] GitHub.DistributedTask.WebApi.AccessDeniedException: Runner version v2.308.0 is deprecated and cannot receive messages.
> 
> ```
> 
> 
> 
> It'd be good if the controller or listener would somehow get notified about errors like this one or if key issues like this would be stored in events for `EphemeralRunner`, so the data is easier to access.
> 
> 
> 
> This is somewhat related, but I can also open a separate issue for this - technically both are about having a way to troubleshoot past runs of a pod that did not succeed to start or finish running a job. Please let me know if this is something I should do.
> 
> 
> 
> ps. Yes, the information about deprecation is in the results of past GitHub actions run, but often the teams managing the infrastructure for runners may not be the ones looking at results from the runners.

@wojciechka I raised an issue for just this specific issue:
- https://github.com/actions/actions-runner-controller/discussions/3118

**Comment by nikola-jokic** [comment]
Closing this one since the new release is out and https://github.com/actions/actions-runner-controller/pull/3074 and https://github.com/actions/actions-runner-controller/pull/3112 covered setting termination reasons
