### ISSUE TITLE
gha-runner-scale-set minIdleRunners

### ISSUE THREAD

**Issue by darintay** [actions/actions-runner-controller#2968]
### What would you like added?
A `minIdleRunners` or `minWarmRunners` option for a runner scaleset, to specify how many warm/idle runners to spin up to be ready for new incoming jobs.

Even when there are many runners already executing active jobs, it would spin up N=`minIdleRunners` extra runners to be ready for the next set of jobs to be requested.

Imagine a loop that every second checked how many active jobs there are and set `minRunners` to that value + N... but ideally implemented more efficiently.

### Why is this needed?
Runners can take a little while to get ready before they're ready to start executing a job.  A warm runner (e.g. one pre-spun-up by `minRunners`) can start executing a job almost instantly.

`minRunners` addresses this need, but only when there are 0 (or <N) active jobs.  Once you have >=N, all jobs must wait for a newly spun up runner, and in a busy CI system that might be the case near 100% of the time, unless you set N to your peak expected runner count, which sort of defeats the purpose of autoscaling.

A `minIdleRunners` values would continue to provide utility when there are potentially many active jobs, and so would be more generally useful.

### Additional context
I might try using the loop described above at some point, but it seems like a lot of polling, and I'm not sure how happy ARC will be with the rapidly changing config value - but might work OK.

**Comment by zhuoyang** [comment]
seems like duplicated https://github.com/actions/actions-runner-controller/issues/2707

**Comment by darintay** [comment]
Ah, I missed that, yep same idea, will close.
