### ISSUE TITLE
feat: containerMode kubernetes mode to support 

### ISSUE THREAD

**Issue by Ravio1i** [actions/actions-runner-controller#2977]
### What would you like added?

Currently when running `containerMode.type: kubernetes` it will require to specify a container job in workflows. I understand why this is a limitation, since it's using the [runner-container-hook](https://github.com/actions/runner-container-hooks) to create an additional container within the cluster. However, the question is whether it is possible to run without any container job, by adding some check whether its not having any container and then just executing normally on the already existing runner container.

### Why is this needed?

We wouldn't like to enforce our developers to just rely on containers. However, the `dind` Mode is no option, because of security limitations in our clusters. Although we may can deploy a single container, it would quite make the life easier to have the same `runs-on` statement for any arc containers.

**Comment by nikola-jokic** [comment]
Hey @Ravio1i,

There is a configuration env variable that disables required job container: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#configuring-kubernetes-mode. By setting `ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER` to "false", the job container would not be required. :relaxed:

**Comment by Ravio1i** [comment]
Oh thank you! I was not aware!
