### ISSUE TITLE
Adding /repos/{owner}/{repo}/actions/runner-scale-sets endpoint and documenting it

### ISSUE THREAD

**Issue by wherka-ama** [actions/actions-runner-controller#2990]
### What would you like added?

With the transition to ARC v2 aka gha-runner-scale-set we lost the capability to fetch the list of the runners filtered by the label.

Previously it was possible to fetch them using the REST call to `/repos/{owner}/{repo}/actions/runners` [doc](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#list-self-hosted-runners-for-a-repository)

The Web UI clearly shows both types. The runners as well as the runner scale sets are included in `https://github.com/organizations/<orgs>/settings/actions/runners`.

However, it's not possible to fetch this information from the REST API, so we cannot really monitor it anymore from this angle. The only reliable way is to check it from the platform the runners are hosted on, which makes this process a bit more cumbersome than just looking up the GH API.

### Why is this needed?

We need it for a simple monitoring. It would also be nice to have these API endpoints to be consistent with the WebUI.

### Additional context

N/A

**Comment by Link-** [comment]
Hey @wherka-ama - thank you for your suggestion. Could you please re-create this issue in: https://github.com/orgs/community/discussions/categories/actions and then share the link with your GitHub representative to pass through the right channels?

Closing this for now as we don't take feature requests through this repository.
