### ISSUE TITLE
Support for `make` command in ubuntu 22.04 runners.

### ISSUE THREAD

**Issue by punit-kulal** [actions/actions-runner-controller#3000]
### What would you like added?

Add build-essentials or make in 22.04 runner.

### Why is this needed?

It's a common pattern to include a Makefile in any project, and use make command to execute tests, formatting, linting etc. However, `build-essential` package was removed in [MR](https://github.com/actions/actions-runner-controller/pull/2050) which included the support for make commnand. `make` command is also available on github provided runners. The reason given was it's niche, which is definitely not the case as Makefile is widely adopted in leading open source projects.

### Additional context

We can include either make or build essential package to start supporting the make command.

**Comment by corford** [comment]
This is affecting us too. Removing build-essential has broken a load of our workflows that use `make` (as the package name implies, having `make` available is kind of essential for a lot of build stuff).

**Comment by pdonorio** [comment]
Found the same issue.

What's the process to build our own image in the meantime, while this gets evaluated?

Just create and push one on top of `ghcr.io/actions/actions-runner:latest` and then use

```
template:
  spec:
    containers:
      - name: runner
        image: own/image:0.0.1
```
?

**Comment by georgekaz** [comment]
considering github actions is a build tool, removing build-essential from the image seems like a very strange decision. Having to download 100Mb with apt on each run is so much worse than having it all in a slightly larger pre-built cached image layer. Please seriously consider adding build-essential back to the image.
For now I make my own image FROM yours.

**Comment by amoralesc** [comment]
Hey @georgekaz, any chance you can share some info about how to build an image based on this one and replace it within the runner set? There is so little info about how to do this, and adding `build-essential` to our images seems like a necessity.

**Comment by mumoshu** [comment]
Hey everyone!

Ubuntu 22.04 images are never meant to align fully with the GitHub-hosted runner VM images as, as we realized when maintaining 20.04 images, it is basically impossible to decide what is "worth" being included in the image- it depends on who uses it and there's no single answer.

So, (don't remember the specific issue but) the decision was to keep 22.04 images minimal, even smaller than 20.04 images. It's supposed to be a base image that you can use either way:

- Have some steps to run "apt-get install" and various "setup-whatever" actions to install necessary commands
- Have a custom runner image based on the community-maintained 22.04 image, do "apt-get install" and others in Dockerfile.

> However, build-essential package was removed in https://github.com/actions/actions-runner-controller/pull/2050

This is not really correct from my perspective.
We made 22.04 images more sustainable and maintainable than 20.04 images. There was no intention of adding `build-essential` or whatever in 22.04 images, from the start.

**Comment by mumoshu** [comment]
So, to be clear, we need to close this issue and similar ones as "wontfix".

The way to go would be to have separate places to maintain more variants of community-maintained runner images.
An example is my https://github.com/actions-runner-controller/runner-images, which is still half-baked as I have no much time to work on this these days.

Thanks for your patience and understanding 🙏

**Comment by georgekaz** [comment]
> Hey @georgekaz, any chance you can share some info about how to build an image based on this one and replace it within the runner set? There is so little info about how to do this, and adding `build-essential` to our images seems like a necessity.

Hi @amoralesc , this is a stripped down version of what I have (I also install other things I want like kubectl/helm/buildx) and I push this to my own image repo. Then I just reference that image here: https://github.com/actions/actions-runner-controller/blob/master/charts/actions-runner-controller/values.yaml#L54C3-L54C32 but I don't know how you're deploying your runners so that might not make sense for you.

```
FROM summerwind/actions-runner:ubuntu-22.04
USER root
RUN apt-get update -qy \
    && apt-get install -y --no-install-recommends --fix-missing \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
USER runner
```
Edit:
Actually I also have an extended chart to add runnersets so my setup is slightly different, but the principal is the same
```
{{- if .Values.runnerSet.create }}
{{- range $index, $runner := .Values.runnerSet.runners }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
.....
    spec:
      containers:
      - name: runner
        {{- if $runner.image }}
        image: {{ $runner.image }}
        {{- end }}
.....
```
Edit2: I schedule rebuilds of my image to make sure I get the updates when the base is updated.
