### ISSUE TITLE
Scale Set Listener is stuck offline in GitHub but pod is still running without errors

### ISSUE THREAD

**Issue by krische** [actions/actions-runner-controller#3005]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

1. Deploy Runner Scale Set, it connects successfully.
2. Let time pass
3. Eventually (in my setup) the runner set may go "offline" in GitHub.
    * The listener pod is still running but the logs just stop at the time it went offline.
    * If the minimum runners in the set is greater than 0, those runners are still online and idle. But the listener appears to remain stuck offline.
4. Deleting the listener pod causing a recreation/restart immediately fixes the issue.

### Describe the bug

With my setup, it is not consistent for how long it takes the listener to go offline, sometimes several days or sometimes less than 24 hours. I suspect it is some kind of network issue that the listener is not recovering from.

If the listener gets disconnected or is unable to refresh GitHub app token for a short period of time, does it not automatically recover or does the container not exit causing kubernetes to restart it?

Manually restarting the listener container fixes the issue.

### Describe the expected behavior

I would expect the listener to be able to gracefully handle network interruptions. Or perhaps the listener pod has some sort of liveness probe to detect it is offline and restarts it.

### Additional Context

`gha-runner-scale-set-controller` chart was deployed with no changes to values.
`gha-runner-scale-set` chart was deployed with:

```yaml
githubConfigSecret: <k8s-secret-with-github-app-credentials>
githubConfigUrl: https://github.com/<my-org>
runnerGroup: <runner-group-i-created>
```

### Controller Logs

There is nothing in the controller logs when the scale set listener went offline. And the last lines I see in the listener logs appear to just be refreshing a GitHub App token:

```shell
2023-10-19T12:37:46Z    INFO    refreshing_client       message queue token is expired during GetNextMessage, refreshing...
2023-10-19T12:37:46Z    INFO    refreshing token        {"githubConfigUrl": "https://github.com/<my-org>"}
2023-10-19T12:37:46Z    INFO    getting access token for GitHub App auth        {"accessTokenURL": "https://api.github.com/app/installations/<my-github-app>/access_tokens"}
2023-10-19T12:37:46Z    INFO    getting runner registration token       {"registrationTokenURL": "https://api.github.com/orgs/<my-org>/actions/runners/registration-token"}
2023-10-19T12:37:46Z    INFO    getting Actions tenant URL and JWT      {"registrationURL": "https://api.github.com/actions/runner-registration"}
```

### Runner Pod Logs

Nothing in runner logs

**Comment by Link-** [comment]
@krische - Please create a GitHub support ticket: https://support.github.com/ and provide us with:
1. The `values.yaml` file you're using for both the `gha-runner-scale-set-controller` and `gha-runner-scale-set`
2. The logs for the controller-manager and listener pods
3. A list of the pods showing the termination

We'll have a look from there

**Comment by arnemorten** [comment]
I just wanted to say I'm facing the same exact issue. It works the day I install it and then over night the runner scale set will show as offline in my github-repo. I can't find any relevant logs.

I'm running on AKS (Free tier) and have installed using helm.

Controller is installed using chart : oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller  version 0.6.1 without any helm values file.

For the runner-scale-set I'm using this chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set version 0.6.1

With these options:
`
helm_options="--set githubConfigUrl=${GITHUB_CONFIG_URL} --set githubConfigSecret.github_token=${GITHUB_PAT} --set template.spec.containers[0].name=runner --set template.spec.containers[0].image=${CUSTOM_IMAGE} --set template.spec.containers[0].command={/home/runner/run.sh} --set minRunners=${MIN_RUNNERS} --set maxRunner=${MAX_RUNNERS}"`


Update: 
Downgrading to 0.6.0 solved it for now. 
Update2: spoke to soon. Still same issue

**Comment by anwarnk** [comment]
@arnemorten @krische did you manage to resolve this issue? We are experiencing the exact same thing.

**Comment by arnemorten** [comment]
@anwarnk No. I just set up a cronjob to restart the listener every night. I have not tested removing the cronjob after upgrading to 0.7.0

**Comment by krische** [comment]
> @arnemorten @krische did you manage to resolve this issue? We are experiencing the exact same thing.

I updated to the latest release but still experience the same thing. I should just setup a cronjob too.

**Comment by Link-** [comment]
@krische @arnemorten @anwarnk - are you all using managed clusters? If not, where are your clusters?

**Comment by krische** [comment]
> @krische @arnemorten @anwarnk - are you all using managed clusters? If not, where are your clusters?

AKS cluster

**Comment by arnemorten** [comment]
AKS.

fre. 15. des. 2023, 14:55 skrev Brian Krische ***@***.***>:

**Comment by anwarnk** [comment]
@Link- We are using AKS 1.27.7.

**Comment by nicolas-laduguie** [comment]
EKS here

**Comment by q-leobrack** [comment]
Hello, any update on this? I don't think it should be closed.

We are experiencing the same problem where the listeners get into a broken state (can be caused by numerous things I would imagine, but in our case it is egress connectivity dropping) and because they have no health probes they do not get restarted by Kubernetes. 

We have to manually delete these pods for them to get them back into a healthy state.

**Comment by michel-numan** [comment]
Happening here on GKE Scaled Set Runner
