### ISSUE TITLE
CA in environment can be too long causing the listener to error

### ISSUE THREAD

**Issue by ldaneliukas** [actions/actions-runner-controller#3020]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Deploy Actions Runner Scale Set Controller to Kubernetes
2. Deploy Actions Runner Scale Set to Kubernetes with a custom CA that contains a lot of certificates.
```

The kubernetes listener fails with:
```
# k logs kubernetes-56cc585c-listener                                                                                 
standard_init_linux.go:228: exec user process caused: argument list too long
```

### Describe the bug

IMHO the listener fails because everything that is found in the referenced CA is added as an environment variable which is passed as an argument causing it to fail with the above error. Describing the pod shows the full contents of that configmap in the pods environment variables:

```
Environment:
  GITHUB_SERVER_ROOT_CA: # The whole CA that can have thousands of lines here.
```

### Describe the expected behavior

The CA is added to the runner containers and used for communication with internal resources that use an internal CA.

### Additional Context

Values:
```yaml
  githubServerTLS:
    runnerMountPath: /usr/local/share/ca-certificates/
    certificateFrom:
      configMapKeyRef:
        name: ca-bundle
        key: ca-certificates.crt
```

### Controller Logs

```shell
{"severity":"info","ts":"2023-10-24T12:46:15Z","logger":"AutoscalingListener","message":"Creating a listener pod","autoscalinglistener":"github/kubernetes-56cc585c-listener"}
{"severity":"info","ts":"2023-10-24T12:46:15Z","logger":"AutoscalingListener","message":"Creating listener pod","autoscalinglistener":"github/kubernetes-56cc585c-listener","namespace":"github","name":"kubernetes-56cc585c-listener"}
{"severity":"info","ts":"2023-10-24T12:46:15Z","logger":"AutoscalingListener","message":"Created listener pod","autoscalinglistener":"github/kubernetes-56cc585c-listener","namespace":"github","name":"kubernetes-56cc585c-listener"}
{"severity":"info","ts":"2023-10-24T12:46:19Z","logger":"AutoscalingListener","message":"Listener pod failed, deleting it and re-creating it","autoscalinglistener":"github/kubernetes-56cc585c-listener","namespace":"github","name":"kubernetes-56cc585c-listener","reason":"","message":""}
```

### Kubernetes listener logs

```shell
standard_init_linux.go:228: exec user process caused: argument list too long
```

**Comment by nikola-jokic** [comment]
Hey @LDaneliukas,

The problem arises when the certificate chain is too large to be written as an environment variable. [This PR](https://github.com/actions/actions-runner-controller/pull/2965) that will be part of the next release should eliminate this problem. You can test it by running [canary image](https://github.com/actions/actions-runner-controller/pkgs/container/gha-runner-scale-set-controller) :relaxed: 

Could you please update the issue title and let us know if the issue persists even with the canary image?

**Comment by ldaneliukas** [comment]
@nikola-jokic thanks for the PR, I haven't noticed it before. Yes, it solves this issue that we're having 👍
