### ISSUE TITLE
No repository included in `job_execution_duration_seconds` metric

### ISSUE THREAD

**Issue by elcidowneador** [actions/actions-runner-controller#3031]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

ArgoCD

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Curl to the listener pod to the /metrics endpoint
2. Find `gha_job_execution_duration_seconds_bucket`
3. Got this result:


gha_job_execution_duration_seconds_bucket{enterprise="",event_name="push",job_name="Build",job_result="succeeded",job_workflow_ref="xxxx/xxxxx/.github/workflows/main.yaml@refs/heads/staging",organization="xxxx",repository="",runner_id="33754",runner_name="xxx-runner-large-x64-l2zlt-runner-ftplx",le="+Inf"} 1

```

### Describe the bug

I want to create a list in my observability dashboard to create a top list of the repositories that consuming more minutes, and also, to create a global sum of minutes used in our runners, but the repository string given by the metrics is empty, as you can see in the previous description.

### Describe the expected behavior

Get a repository with the repository name that triggered the workflow.

### Additional Context

```yaml
---
```

### Controller Logs

```shell
2023-10-27T07:54:28Z    INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
2023-10-27T07:54:28Z    INFO    Registering scale set metrics
2023-10-27T07:54:28Z    INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
```

### Runner Pod Logs

```shell
----
```

**Comment by nikola-jokic** [comment]
Hey @elcidowneador,

Are the scale set registered on the org level? If that is the case, the repository will be empty since the scale set does not belong to a repository

**Comment by elcidowneador** [comment]
Hello @nikola-jokic,

Thank you for answering. Yes, this scale is registered at the org level, but in this case, there is no way to get the repository for this kind of metric? because i want to get build time per repository.

**Comment by nikola-jokic** [comment]
Thank you for confirmation! The way the metrics are structured is, so you can query them by the scale set configuration. If you feel like it should work differently, can you please submit it to the [Community Forum](https://github.com/orgs/community/discussions/categories/actions)?
I will close this issue here since it would be considered as feature request, and they should be created by using this forum :relaxed:
