### ISSUE TITLE
ARC install using helm and flux install runs into 403 permission errors

### ISSUE THREAD

**Issue by ryanobjc** [actions/actions-runner-controller#3041]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

n/a irrelevant

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. run helm pull oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
2. error:
Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden


When I use FluxCD to do this, I get a similar error in the HelmChart object:
kubectl get helmchart -n ci
NAME                       CHART                             VERSION   SOURCE KIND      SOURCE NAME   AGE   READY   STATUS
ci-github-arc-controller   gha-runner-scale-set-controller   0.6.1     HelmRepository   github-arc    18h   False   chart pull error: failed to download chart for remote reference: failed to get 'oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller/gha-runner-scale-set-controller:0.6.1': failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%!!(MISSING)A(MISSING)actions%!!(MISSING)F(MISSING)actions-runner-controller-charts%!!(MISSING)F(MISSING)gha-runner-scale-set-controller%!!(MISSING)F(MISSING)gha-runner-scale-set-controller%!!(MISSING)A(MISSING)pull&service=ghcr.io: 403 Forbidden


The instructions in https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller in this case do not actually work.  For example following the command literally:

$ helm install arc \
>     --namespace "${NAMESPACE}" \
>     --create-namespace \
>     oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
Error: INSTALLATION FAILED: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden
```

### Describe the bug

The documentation either needs to be updated noting that there is no such thing as public access to OCI repositories, and all repository access must be authenticated and logged against your personal github identity.... Or the OCI repository needs to be fixed to match the documented intent: public/anonymous non-logged in access.

If you really want to do the former, it would be nice to include some instructions that cover server-side deployments using fluxcd which is the most popular CD tool for k8.  ArgoCD as a second nice to have.  The usual "just run docker login" doesn't work on a remote controller/operator and specific configuration examples would be very helpful for people who are just trying to figure out if Github Actions is worth using. It might be free but time isn't.

### Describe the expected behavior

I expected my helm charts to install. 

### Additional Context

```yaml
Can't even install the non-configured gha-scale-set-controller, so there is no values.yaml
```

### Controller Logs

```shell
it didn't even run.
```

### Runner Pod Logs

```shell
Nothing is able to be installed. See above for specific helm install failure logs.
```

**Comment by nikola-jokic** [comment]
Hey @ryanobjc,

Can you please check if it works now? Maybe it was a temporary error, but the chart should be available. To confirm the chart is available, I did spin up an empty ubuntu container and installed helm. I managed to pull the oci image without any issues, so it is possible that the error was temporary.

**Comment by ryanobjc** [comment]
So I tried with helm this morning, and it didn't work.  I updated helm from 3.13.0 -> 3.13.1 and now it works...  My flux 'helm-controller' is on version 0.36.2 which is current. 

The helm release notes for 3.13.1 doesn't seem to indicate any particular fixes in this area. 

Could the server side be blocking non-current user-agents?

**Comment by nikola-jokic** [comment]
By reading the release, it seems like there is a fix in `3.13.1` for [anonymous pull](https://github.com/helm/helm/commit/0ac78941abfed981a47f263fa59931e9123f73a1)
Closing this one since it is not related to ARC

**Comment by propyless** [comment]
So sorry for commenting on a closed ticket, but I am also getting this same issue with 3.13.2 of helm, also getting the same error message as @ryanobjc  in flux and I can't pull with helm either.

```
❯ helm version
version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.20.10"}

❯ helm pull oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller --version 0.7.0
Error: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%3Apull&service=ghcr.io: 403 Forbidden

❯ helm pull oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller:0.7.0
Error: GET "https://ghcr.io/v2/actions/actions-runner-controller-charts/gha-runner-scale-set-controller/tags/list": GET "https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%3Apull&service=ghcr.io": unexpected status code 403: denied: denied

❯ flux --version
flux version 0.41.
```

How are you pulling the charts @ryanobjc?

Seems it works when i'm auuthenticated
`❯ gh auth token | helm registry login ghcr.io -u propyless --password-stdin`

Do you have to be authenticated? there is no anonymous pull?

**Comment by ryanobjc** [comment]
There seems to be spurious issues with ghcr.io that come and go.  

Also turns out in my flux config I had specified some of the path components twice.  Adding "oci://ghcr.io/actions/actions-runner-controller-charts" as the repo url, then specify only "gha-runner-scale-set-controller" as the chart.  I think I had accidentally included the "actions-runner-controller-charts" twice.  That seemed to be my flux problem.

But I definitely couldn't pull unauthenticated, then the next day it worked.

**Comment by propyless** [comment]
Aha.. spurious issues with ghcr. Well, I guess its fine to have a packages:read classical token configured for ghcr.io.

Strange issue to say the least.. glad you got flux working.

**Comment by snps-madduk** [comment]
> So sorry for commenting on a closed ticket, but I am also getting this same issue with 3.13.2 of helm, also getting the same error message as @ryanobjc in flux and I can't pull with helm either.
> 
> ```
> ❯ helm version
> version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.20.10"}
> 
> ❯ helm pull oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller --version 0.7.0
> Error: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%3Apull&service=ghcr.io: 403 Forbidden
> 
> ❯ helm pull oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller:0.7.0
> Error: GET "https://ghcr.io/v2/actions/actions-runner-controller-charts/gha-runner-scale-set-controller/tags/list": GET "https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%3Apull&service=ghcr.io": unexpected status code 403: denied: denied
> 
> ❯ flux --version
> flux version 0.41.
> ```
> 
> How are you pulling the charts @ryanobjc?
> 
> Seems it works when i'm authenticated `❯ gh auth token | helm registry login ghcr.io -u propyless --password-stdin`
> 
> Do you have to be authenticated? there is no anonymous pull?

Hi I also faced the same issue but when deploying as Helm chart using Harness CD.
When adding a connector with no credentials I am getting unauthorized error, where as when credentials are given the deployment is working fine.

I don't know why harness can't pull the chart without credentials,.

**Comment by seilorjunior** [comment]
I am also having the same issue following the https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller

**Comment by zegomess** [comment]
I was having the same permission error, but im using argocd at the moment

> There seems to be spurious issues with ghcr.io that come and go.
> 
> Also turns out in my flux config I had specified some of the path components twice. Adding "oci://ghcr.io/actions/actions-runner-controller-charts" as the repo url, then specify only "gha-runner-scale-set-controller" as the chart. I think I had accidentally included the "actions-runner-controller-charts" twice. That seemed to be my flux problem.
> 
> But I definitely couldn't pull unauthenticated, then the next day it worked.

this helped me a lot, its crazy that I was too setting `gha-runner-scale-set-controller` twice and reading this helped me double check this and started running and ArgoCD was able to deploy correctly the controller and the `gha-runner-scale-set` helm chart as well

**Comment by hazarguney** [comment]
I’m facing the same problem as well.

**Comment by smallc2009** [comment]
> I’m facing the same problem as well.

I had the same issue and ended up loging in ghcr.io

solution:
```
ubuntu@k8s-261038:~/linux-arm64$ helm registry login ghcr.io -u [username]
Password:
Login Succeeded

ubuntu@k8s-261038: NAMESPACE="arc-systems"
ubuntu@k8s-261038:~/linux-arm64$ helm install arc --namespace "${NAMESPACE}"  --create-namespace oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
Pulled: ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller:0.11.0
Digest: sha256:35003eb7db8bba6dbf4f3df1d637959d938f7a8d7fad5640de9b5f5f834e1b0b
NAME: arc
LAST DEPLOYED: Fri Apr 11 07:57:07 2025
NAMESPACE: arc-systems
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing gha-runner-scale-set-controller.

Your release is named arc
```

**Comment by johnknutsonhc** [comment]
I am currently experiencing this as well.

**Comment by smarticu5** [comment]
I'm also facing this problem today.  I can get a token when using my browser or curl, but helm is failing.

**Comment by pspittelmeister** [comment]
Please reopen, I am currently facing the same problem with argocd. The token is a classic token with red:package permissions. I also tried the most recent version as of today, 0.12.1 but same problem

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc-in-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: staging
  sources:
    - repoURL: oci://ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set-controller
      targetRevision: 0.12.0
      helm:
        releaseName: github-arc-controller
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/environments/staging/values/github-arc/controller.yaml
    - repoURL: oci://ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: 0.12.0
      helm:
        releaseName: github-arc-runners
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/environments/staging/values/github-arc/runners.yaml
    - repoURL: ssh://git@github.com/XXXXX/XXXXX.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: github-arc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # We use SSA because runners are controller managed objects
```


```
~ » k describe secrets argocd-ghcr-read-token
Name:         argocd-ghcr-read-token
Namespace:    argocd
Labels:       argocd.argoproj.io/secret-type=repo-creds
Annotations:  operator.1password.io/item-path: vaults/XXXXX/items/XXXXX
              operator.1password.io/item-version: 5

Type:  Opaque

Data
====
name:       22 bytes
password:   40 bytes
type:       4 bytes
url:        48 bytes
username:   15 bytes
enableOCI:  4 bytes
```
