### ISSUE TITLE
Unable to customize dind container.

### ISSUE THREAD

**Issue by guguducken** [actions/actions-runner-controller#3085]
### Checks

- [x] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.7.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. set containerMode.type to dind
2. change dind container setting in template.spec.containers.dind
3. apply gha arc by `helm install`
```

### Describe the bug

Unable to customize dind container. By observing the template, I found template do not use customer dind setting, it just use default setting which in `_helpers.tpl` https://github.com/actions/actions-runner-controller/blob/8aa04dd2beddce108a759afd6bf4ea95640a270e/charts/gha-runner-scale-set/templates/_helpers.tpl#L98-L116

### Describe the expected behavior

gha arc should use customer dind setting

### Additional Context

```yaml
none
```

### Controller Logs

```shell
none
```

### Runner Pod Logs

```shell
none
```

**Comment by nikola-jokic** [comment]
Hey @guguducken,

It is documented [here](https://github.com/actions/actions-runner-controller/blob/8aa04dd2beddce108a759afd6bf4ea95640a270e/charts/gha-runner-scale-set/values.yaml#L75) that we do not support customizations of dind or k8s mode. If customization is required, please keep containerMode object commented out, and provide a side-car container. We also documented how our default configuration is applied so it can be used as a starting point.
