### ISSUE TITLE
Unable to set custom dind image

### ISSUE THREAD

**Issue by LillyHolden-Tide** [actions/actions-runner-controller#3120]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
In the values file for the gha-runner-scale-set specify:
template:
  spec:
    containers:
      - name: runner
        image: my-registry/runner:123
        command: ["/home/runner/run.sh"]
      - name: dind
        image: my-registry/dind:456
```

### Describe the bug

New runner is correctly configured with my custom runner image, however dind sidecar is still using docker:dind as that has been hardcoded here:https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/_helpers.tpl#L99

### Describe the expected behavior

I would expect dind sidecar to use my-registry/dind:456 image

### Additional Context

```yaml
as above
```

### Controller Logs

```shell
n/a
```

### Runner Pod Logs

```shell
n/a
```

**Comment by nikola-jokic** [comment]
Closing this one as it is described in the following [discussion](https://github.com/actions/actions-runner-controller/discussions/3117)
