### ISSUE TITLE
GH Autoscaled Set does not seem to scale more than the minRunners

### ISSUE THREAD

**Issue by pavlospt** [actions/actions-runner-controller#3137]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.7.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
- Deploy GHA controller
- Set minRunners to a number
- The number of runners is scaled up and stays the same forever
```

### Describe the bug

Even though I am using autoscaled sets, I have never observed the scale set, scaling to more than the `minRunners`.

### Describe the expected behavior

Scale whenever there are more jobs to be ran.

### Additional Context

```yaml
-
```

### Controller Logs

```shell
https://gist.github.com/pavlospt/3295a6d447a493dc10f9c66cba09c9ca
```

### Runner Pod Logs

```shell
-
```

**Comment by nikola-jokic** [comment]
Hey @pavlospt,

Can you also share the listener log? In the current version, if the number of acquired jobs is less than min runners, we don't need to scale up in order to run them, so the number of min runners are able to handle it. We are going to introduce a change in semantics of min runners according to [this ADR](https://github.com/actions/actions-runner-controller/blob/master/docs/adrs/2023-11-02-min-runners-strategy.md), but right now, if the number of min runners is sufficient to handle the workload, we won't scale up :relaxed:

**Comment by pavlospt** [comment]
Hello @nikola-jokic , since the listener pod logs contain sensitive info (in terms of repo names etc.) I can share the following log I observed: 
```
service	current runner scale set statistics.	{"available jobs": 0, "acquired jobs": 6, "assigned jobs": 6, "running jobs": 6, "registered runners": 6, "busy runners": 6, "idle runners": 0}
```

`minRunners` is set to 5, does the above mean that it has scaled to 6 and I can never spot it in live action due to jobs being fast & finishing quite shortly? 

I guess the proper way to check that would be to expose metrics and log them in Prometheus or something. Am I understanding this properly?

**Comment by nikola-jokic** [comment]
Can you try maybe scheduling a matrix of 10 or more jobs, you should spot the difference :relaxed: 
Or maybe create a testing job that only sleeps for 20s for example

**Comment by pavlospt** [comment]
Will check it again and let you know. Is there any obvious way of exposing metrics from the controller or the listener?

**Comment by pavlospt** [comment]
I have confirmed it with a test matrix and it works as expected! Sorry for the confusion & thank you for your assistance!
