### ISSUE TITLE
v0.7.1 release for ghat-runner-scale-set

### ISSUE THREAD

**Issue by utam0k** [actions/actions-runner-controller#3164]
### What would you like added?

Why don't you release a new patch version for the gha-runner-scale-set?

### Why is this needed?

I'd like to use the new feature, and it's a good time to release a new patch version.

### Additional context

Changelog:

- Change minRunners behavior and fix the new listener min runners [#3139](https://github.com/actions/actions-runner-controller/pull/3139)
- Modify user agent format with subsystem and is proxy configured information [#3116](https://github.com/actions/actions-runner-controller/pull/3116)
- Record the error when the creation pod fails [#3112](https://github.com/actions/actions-runner-controller/pull/3112)
- Set actions client timeout to 5 minutes, add logging to client [#3103](https://github.com/actions/actions-runner-controller/pull/3103)
- Refactoring listener app with configurable fallback [#3091](https://github.com/actions/actions-runner-controller/pull/3096)
- Record a reason for pod failure in EphemeralRunner [#3074](https://github.com/actions/actions-runner-controller/pull/3074)

*Add any other context or screenshots about the feature request here.*

**Comment by utam0k** [comment]
Hi @Link- and @nikola-jokic. Why don't you release a new patch version for `gha-runner-scale-set`? I tried to prepare for it https://github.com/actions/actions-runner-controller/pull/3163

**Comment by Link-** [comment]
Thank you @utam0k but we're working on a bigger 0.8.0 release that's coming out soon. This is going hand-in-hand with a docs.github.com update. Please standby.

**Comment by utam0k** [comment]
@Link- Thanks for taking your look. I'm looking forward to `v0.8.0` 🚀
