### ISSUE TITLE
gh-runner-set 0.8.0 proxy issue

### ISSUE THREAD

**Issue by dmitrijrub** [actions/actions-runner-controller#3178]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
helm upgrade --install arc-runner-set \
            --namespace ${{ steps.set-vars.outputs.namespace }} \
            oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set \
            --version 0.8.0 \
            --kube-apiserver=${{ secrets.KUBE_APISERVER }} \
            --kube-token=${{ secrets.KUBE_TOKEN }} \
            --set githubConfigSecret.github_app_id=${{ secrets.APP_ID }} \
            --set githubConfigSecret.github_app_installation_id=${{ secrets.APP_INSTALLATION_ID }} \
            --set githubConfigSecret.github_app_private_key='${{ secrets.APP_PRIVATE_KEY }}' \
            -f ./helm/$environment/arc-runner-set-values-flavered.yaml \
            --values=${{ matrix.flavor }} \
            --atomic
```

### Describe the bug

in 0.7.0 i have proxy defined in arc-runner-set-values-flavered.yaml as:
***
proxy:
  http:
    url: http://abc:8080
  https:
    url: http://abc:8080
  noProxy:
    - 127.0.0.1
    - 10.43.0.1 
***

after upgrade to 0.8.0 listener returns error:
2023-12-20T15:03:44.857132481+01:00 2023-12-20T14:03:44Z	INFO	listener-app	getting access token for GitHub App auth	{"accessTokenURL": "https://api.github.com/app/installations/XXXX/access_tokens"}
2023-12-20T15:04:14.869538367+01:00 2023-12-20T14:04:14Z	ERROR	listener-app	Retryable client error	{"error": "Post \"https://api.github.com/app/installations/XXXX/access_tokens\": dial tcp 140.82.121.6:443: i/o timeout", "method": "POST", "url": "https://api.github.com/app/installations/XXXX/access_tokens", "error": "request failed"} 

### Describe the expected behavior

expectation that proxy will keep on working

### Additional Context

```yaml
rolled back to 0.7.0 and back to 0.8.0 to confirm the issue
```

### Controller Logs

```shell
there are no issue with controller
```

### Runner Pod Logs

```shell
2023-12-20T15:03:44.857132481+01:00 2023-12-20T14:03:44Z	INFO	listener-app	getting access token for GitHub App auth	{"accessTokenURL": "https://api.github.com/app/installations/XXXX/access_tokens"}
2023-12-20T15:04:14.869538367+01:00 2023-12-20T14:04:14Z	ERROR	listener-app	Retryable client error	{"error": "Post \"https://api.github.com/app/installations/XXXX/access_tokens\": dial tcp 140.82.121.6:443: i/o timeout", "method": "POST", "url": "https://api.github.com/app/installations/XXXX/access_tokens", "error": "request failed"}
```

**Comment by nikola-jokic** [comment]
Hey @dmitrijrub,

I think I know what is the issue. Can you please check if it affects the original client in version 0.8.0? 

To do that, please add the following to the controller values.yaml file:

```yaml
env:
  - name: LISTENER_ENTRYPOINT
    value: /github-runnerscaleset-listener
```

**Comment by dmitrijrub** [comment]
thanks, look like it worked! 
can you explain more what caused the problem?
there are no mentioning of setting listener entry point in https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set-controller/values.yaml

**Comment by nikola-jokic** [comment]
Sorry for that, and thank you for raising this issue and checking if the issue is with the new listener!

We did a [refactoring of the listener app](https://github.com/actions/actions-runner-controller/pull/3096), and it seems like the proxy option was missing, unfortunately. And because of it, we did create a mechanism to fall back to the original implementation in case we encounter a bug, so it does not block people from upgrading.

**Comment by nikola-jokic** [comment]
Hey @dmitrijrub,

Again, thank you for submitting the issue :relaxed:! We published a patch release that should fix the problem on the newest listener. If you can, when you upgrade, please let us know if it solves the issue you had :relaxed:

**Comment by dmitrijrub** [comment]
Thanks again @nikola-jokic , i have removed env variable and set helm chart version to 0.8.1 - everything works fine

**Comment by shankarRaman** [comment]
@dmitrijrub I am running into an issue where the proxy is not getting honored. When you do a `kubectl describe pod` on your controller pod, are you seeing the `http_proxy, https_proxy` variables set for the `Manager` container?
