### ISSUE TITLE
Min idle runners

### ISSUE THREAD

**Issue by marverix** [actions/actions-runner-controller#3200]
### What would you like added?

`minIdleRunners` - property to set number of minimum idle runners.

Eg.

`minIdleRunners: 1` 
no builds --> runner A (idle)
1 build started --> runner A (taken) + runner B (idle)

### Why is this needed?

Currently, there is a property `minRunners`, which is great. The use case for this flag I understand is that there should eg. a runner waiting. So if a developer starts a build, one does not need to wait to spin the runner (pod) but instead, it is there already. The problem is that with the current approach if eg. one has `minRunners: 1`, and will start a build, the runner will be taken, and another developer will need to wait to spin the runner. Which basically destroys the usability of this flag (from my perspective).

### Additional context

None

**Comment by Link-** [comment]
https://github.com/actions/actions-runner-controller/releases/tag/gha-runner-scale-set-0.8.0
https://github.com/actions/actions-runner-controller/pull/3139
