### ISSUE TITLE
Task step timing is wrong

### ISSUE THREAD

**Issue by moltar** [actions/actions-runner-controller#3202]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.7.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Just running a workflow.
```

### Describe the bug

The working step times seem to be wrong. They are too high, and also do not add up to the total.

### Describe the expected behavior

Steps to report correct time.

![screenshot-20240104T142450-OHPSXQkK@2x](https://github.com/actions/actions-runner-controller/assets/491247/e62dd5df-2c11-47b6-b542-5808b7a669c5)

### Additional Context

```yaml
N/A
```

### Controller Logs

```shell
N/A
```

### Runner Pod Logs

```shell
N/A
```

**Comment by nikola-jokic** [comment]
Hey @moltar,

This issue is not related to ARC, could you please post it on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions)? Posting there can help to route this issue to the correct team :relaxed:

**Comment by moltar** [comment]
> This issue is not related to ARC

Why isn't it related?

I'm running an ARC cluster.

I don't experience the same problem on the hosted version.

**Comment by nikola-jokic** [comment]
It is unrelated since ARC itself does not propagate this information in any way. Once the runner is up, and the job lands on the runner, the runner communicates job information to the actions service. There is nothing we can do on ARC side to fix this issue

**Comment by moltar** [comment]
Should the issue be transferred to the runner repo then? https://github.com/actions/runner

**Comment by nikola-jokic** [comment]
I would still advise you to post it in the forum. I think the runner streams UTC timestamps, and it may be related to the service, but I can't say for sure. Because of that, I would still advise you to post the issue on the Community Support Forum
