### ISSUE TITLE
Runner scale sets are not automatically recreated if they are removed by GitHub API due to inactivity

### ISSUE THREAD

**Issue by adiroiban** [actions/actions-runner-controller#3205]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

1. Install an ARC scale set listener

```
export CHEVAH_ARC_SET_VERSION=0.8.1
export INSTALLATION_NAME="arc-runner-set"
export NAMESPACE="arc-runners"

helm install "${INSTALLATION_NAME}" --version "${CHEVAH_ARC_SET_VERSION}" \
    --namespace "${NAMESPACE}" \
    --create-namespace \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
```

2. Wait for the `Runner scale set` to be created inside GitHub API, check https://github.com/ORG/REPO/settings/actions/runners to make sure it was created
3. Turn your cluster off and leave it offline for 3 weeks
4. Check https://github.com/ORG/REPO/settings/actions/runners to make sure it was removed by GitHub API due to inactivity
5. After that start your cluster
6. Check https://github.com/ORG/REPO/settings/actions/runners again and observe that the scale set is not auto recreated

### Describe the bug

It looks like ARC Helm only creates the scale set at install time.

If the scale set is not active for 14 days, GitHub API will auto-delete the Scale set object ob GitHub.com

If ARC is started, or updated , it will not recreate the scale-set

### Describe the expected behavior

I am expected to have the scale-set automatically recreated if it was removed on GitHub.com

### Additional Context

```yaml
using default values.yaml
```

### Controller Logs

```shell
The errors are in the listener pod.

The listener pod is running.
If I delete the listener pod, it is automatically recreated by the controller, but the error is

 {"error": "404 - had issue communicating with Actions backend: No runner scale set found with identifier 1."}
```

### Runner Pod Logs

```shell
No runners are created.
```

**Comment by nikola-jokic** [comment]
Hey @adiroiban,

This behavior is consistent with the runner behavior. If the runner is left for 2 weeks being offline, you would have to re-register it. Once you start your cluster again, the resources are there, assuming that the scale set exists. This behavior is intentional, but if you feel like it should be otherwise, could you please post your feedback to the [Community Support Forum](https://github.com/orgs/community/discussions/categories/actions)? Using it could help us prioritize feature requests related to ARC :relaxed:

**Comment by adiroiban** [comment]
Thanks for the info. 

By uninstalling the helm chart and installing it again, the runner scale set is (re)created and all works ok.

I don't think that this should be a priority.

I guess that people will not usually leave the k8s cluster offline for more than 2 weeks, so this is not a common use case.


I have reported this, just in case others have a similar error.

--------

So, if you see that the `Runner scale set` is not found in GitHub -> Settings -> Actions page (https://github.com/org/repo/settings/actions/runners), you will need to reinstall the helm chart.

It will not be automatically re-created after install or during upgrade.

-----

Thanks!

**Comment by nikola-jokic** [comment]
No problem! Thank you for reporting it, it may help other people :relaxed: 

The controller is actually responsible for [creating a scale set](https://github.com/actions/actions-runner-controller/blob/47dfed3ced786c117a58cbacedd8b5fb90777882/controllers/actions.github.com/autoscalingrunnerset_controller.go#L191) during installation, and that is why deleting a listener won't help. If you uninstall the scale set (to delete resources) and install it again, it should be up and running without issues. That is a recommended path for upgrades as well, at least for now :relaxed:

**Comment by krupakar1329** [comment]
"All unused runner scale sets will be purged automatically after 24 hours." Does this statement holds true?
 i have a self hosted runner scaleset created at the repository level. Now i want to move it to organization level. but facing the issue
had issue communicating with Actions backend: No runner scale set found with identifier 1."}. 
Once the self hosted runner scaleset is offiline, is it deleted by Github after 24 hours? @nikola-jokic

**Comment by adiroiban** [comment]
> i have a self hosted runner scaleset created at the repository level. Now i want to move it to organization level. 

Easiest option is to install the new scale set at organization level using a different name.

You can't just move/update via the helm chart.

You need to run the install steps in order to create the scaleset.

-------

For the old runner scale set, you can run the `helm uninstall` command
