### ISSUE TITLE
Git disappears with lfs: true

### ISSUE THREAD

**Issue by withinboredom** [actions/actions-runner-controller#3222]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Using mostly defaults, run the following action on a self-hosted runner:


name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true # <-


I've tried `lfs: 'true'`, v2, v3, v4 to no avail. If anything, I would expect `git-lfs` to be missing and not `git`.
```

### Describe the bug

Receive the error:

```
Error: Unable to locate executable file: git. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

### Describe the expected behavior

No error and checkout to work.

### Additional Context

```yaml
N/A
```

### Controller Logs

```shell
N/A
```

### Runner Pod Logs

```shell
https://gist.github.com/withinboredom/56ab54c83d944081b30a14111a5c0234
```

**Comment by withinboredom** [comment]
Ah, it looks like `git` isn't installed in the image? Why would that be the default for something made by GIThub?

**Comment by nikola-jokic** [comment]
Hey @withinboredom,

You are right, git is not installed by default. The idea is to provide a slim image that can be used as a base, or as is. I will close this issue here since there is already a PR that you linked (thank you for doing that :relaxed:), and this issue is not related to ARC itself, but the runner image where the PR is.

**Comment by withinboredom** [comment]
Awesome thanks! Yeah, when this error first showed up I didn't yet know if it were an issue with the action, the image, or arc (since I'd just upgraded from an old old version of this). Either way, I think this issue shows a good use-case for having it installed. Hopefully it will be.

**Comment by mbelot007** [comment]
When will this change be included in a patch release? Still experiencing issues missing git.
