### ISSUE TITLE
Controller logs errors for non-existent pods in previous namespace after moving to new namespace

### ISSUE THREAD

**Issue by theophileds** [actions/actions-runner-controller#3317]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Step 1: Install Helm charts in namespace A

Run the following Helm commands to install the arc and arc-runner-set charts in namespace RUNNER_A:

helm upgrade arc \
    --install \
    --namespace "RUNNER_A" \
    --create-namespace \
    --values values.controller.yaml \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller

helm upgrade arc-runner-set \
    --install \
    --namespace "RUNNER_A" \
    --create-namespace \
    --values values.runner.yaml \
    --set githubConfigUrl="${GITHUB_CONFIG_URL}" \
    --set githubConfigSecret.github_token="${GITHUB_PAT}" \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

Step 2: Run some workflows

Run some GitHub Actions workflows that use the self-hosted runners in namespace RUNNER_A.

Step 3: Uninstall the Helm chart

Run the following Helm commands to uninstall the arc and arc-runner-set charts from namespace RUNNER_A:

helm uninstall arc -n "RUNNER_A"
helm uninstall arc-runner-set -n "RUNNER_A"
Delete namespace RUNNER_A:

kubectl delete namespace RUNNER_A

Step 4: Force remove any old remaining workers in GH runners web UI

Go to the GitHub Actions runner web UI and force remove any old remaining workers that were registered in namespace RUNNER_A.

Step 5: Install the Helm chart in namespace B

Run the following Helm commands to install the arc and arc-runner-set charts in namespace RUNNER_B:

helm upgrade arc \
    --install \
    --namespace "RUNNER_B" \
    --create-namespace \
    --values values.controller.yaml \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller

helm upgrade arc-runner-set \
    --install \
    --namespace "RUNNER_B" \
    --create-namespace \
    --values values.runner.yaml \
    --set githubConfigUrl="${GITHUB_CONFIG_URL}" \
    --set githubConfigSecret.github_token="${GITHUB_PAT}" \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

Step 6: Check the controller logs

Check the logs of the arc controller to ensure that it is running and managing the self-hosted runners in namespace RUNNER_B.
```

### Describe the bug

I initially installed the GitHub Actions controller in a namespace called **github-actions**, but later decided to move it to a different namespace called **github-runner**. I took care of uninstalling the Helm chart, deleting the namespace, and purging the remaining workers on GitHub.

However, since reinstalling the controller, it keeps logging error messages related to non-existent pods in the initial namespace (github-actions). These errors are occurring because the controller has no permission to access the initial namespace.

I'm not sure how the controller is retrieving this information, as I haven't noticed any communication with etcd or external storage in the architecture specifications. I suspect that the information may be collected from the GitHub API, but I cannot find any relevant documentation or parameters to [display](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#list-runner-applications-for-an-organization) hidden/terminating workers when I list the runners.

Despite purging the workers more than 48 hours ago, the controller continues to attempt to access them, and I'm not sure why. I'm seeking assistance in resolving this issue.

### Describe the expected behavior

The controller should not try to delete non-existent runners.

### Additional Context

```yaml
I'm using the default yaml template.
```

### Controller Logs

```shell
2024-03-04T08:01:44Z	ERROR	Reconciler error	{"controller": "ephemeral-runner-controller", "controllerGroup": "actions.github.com", "controllerKind": "EphemeralRunner", "EphemeralRunner": {"name":"arc-runner-set-czn6f-runner-b9r2n","namespace":"github-actions"}, "namespace": "github-actions", "name": "arc-runner-set-czn6f-runner-b9r2n", "reconcileID": "c177652b-9599-4d7d-86a2-0ac93c57656a", "error": "failed to get actions client for runner: failed to get secret: secrets \"arc-runner-set-gha-rs-github-secret\" is forbidden: User \"system:serviceaccount:github-runner:arc-gha-rs-controller\" cannot get resource \"secrets\" in API group \"\" in the namespace \"github-actions\""}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227
```
```


### Runner Pod Logs

```shell
Not relevant.
```

**Comment by deepakjotwani15** [comment]
Facing similar issue.. any update on this?

**Comment by nikola-jokic** [comment]
Hey @theophileds,

I think the problem is the order of steps you ran. You first uninstalled the ARC which removes the controller, then you uninstalled the scale set. Now, when you uninstall the scale set, there is no controller to start deleting resources, so you are left in a bad state.

When you install it again, the controller doesn't have permissions to complete the old cleanup, so it logs the error.

The correct way to switch the namespace would be:
1. Remove the scale set and wait for all resources to be deleted
2. Install the new scale set in a different namespace

There is no need to uninstall ARC, but in case you do need to do that, you would have to uninstall all scale sets, and only then, uninstall ARC controller.

The controller should exist longer than the resources it owns.

**Comment by theophileds** [comment]
Hey @nikola-jokic 

Thanks for your answer.

Should I reinstall the controller in `github-actions` namespace so that it will notify GH servers that these runners no longer exist, or is there a point where GH will stop claiming status on these runners?

**Comment by nikola-jokic** [comment]
[Runners will be automatically cleaned up after 1 day.](https://docs.github.com/en/enterprise-cloud@latest/actions/hosting-your-own-runners/managing-self-hosted-runners/removing-self-hosted-runners#removing-a-runner-from-a-repository) Ideally, you should remove the controller only when you upgrade. Controller is an app wrapped inside the deployment. Everything related to your scale set is managed by them, so if you delete the controller, there will be nothing that can remove or clean up runners and other resources from your cluster. That is one of the reasons why we separated these two charts. If you need to modify the scale set, you should only use `gha-runner-scale-set` chart. I hope this helps :relaxed:

**Comment by theophileds** [comment]
Hey @nikola-jokic,

I understand your explanation, but it has been more than two weeks since I experienced this problem, is this normal?

**Comment by nikola-jokic** [comment]
Do you have ephemeral runner pods that are still running?

**Comment by theophileds** [comment]
Not those listed in the logs.
