### ISSUE TITLE
Wrong Reported Queue time in the Github Workflow UI

### ISSUE THREAD

**Issue by jaswanthikolla** [actions/actions-runner-controller#3346]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.2

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Create a workflow that runs on ARSS 
2. run the workflow, "Set up Job" waits for the ARSS runner to be available.
3. Reported Queue time is either 0s or 2s regardless of the wait time.
```

### Describe the bug

Github Action's UI reported Setup job's Queue time is wrong. 
<img width="1251" alt="image" src="https://github.com/actions/actions-runner-controller/assets/95378959/93dab511-6463-4b17-a24f-d1b221759012">

### Describe the expected behavior

Set up Job time should reflect how long it took to get the runner.

### Additional Context

```yaml
Can be reproduced with any values.yaml
```

### Controller Logs

```shell
NA
```

### Runner Pod Logs

```shell
NA
```

**Comment by nikola-jokic** [comment]
Hey @jaswanthikolla,

Set up job is communicated by the runner, not by ARC. Probably the `job_startup_duration_seconds` is the metric you are looking for. I will close this issue since it is not related to ARC.
