### ISSUE TITLE
Enable node affinity for listener pods and runner pods

### ISSUE THREAD

**Issue by sjm-ho** [actions/actions-runner-controller#3355]
### What would you like added?

I was following this quickstart guide https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller and I would like node affinity support to be added for listener and runner jobs as well.

### Why is this needed?

This would be needed for usecases like when we would need to deploy everything related to github actions arc controller even the runner pods on a specific node group thus segregating the workload types

**Comment by nikola-jokic** [comment]
Hey @sjm-ho,

This Enhancement is related to gha-runner-scale-set, and not the community version. To answer this request, you already have the ability to customize both the [listener pod](https://github.com/actions/actions-runner-controller/blob/753afb75b9dfd3ba7a402630d94a06491fcfcfdf/charts/gha-runner-scale-set/values.yaml#L93), and the [ephemeral runner](https://github.com/actions/actions-runner-controller/blob/753afb75b9dfd3ba7a402630d94a06491fcfcfdf/charts/gha-runner-scale-set/values.yaml#L110) pods. For container jobs, if you are using container mode kubernetes, you can use the [hook extension](https://github.com/actions/runner-container-hooks/blob/main/docs/adrs/0134-hook-extensions.md).

**Comment by sjm-ho** [comment]
Hey @nikola-jokic  I could achieve the same by

# for controller pod
<img width="1507" alt="Screenshot 2024-03-15 at 9 12 55 PM" src="https://github.com/actions/actions-runner-controller/assets/162109584/62d792d7-c6d9-4acf-a7c4-f99a23e9ab72">

# for listener pod
<img width="1507" alt="Screenshot 2024-03-15 at 9 09 14 PM" src="https://github.com/actions/actions-runner-controller/assets/162109584/6914731a-c4ca-4366-8796-a7ee289253ab">

# for runner pod
<img width="1507" alt="Screenshot 2024-03-15 at 9 09 21 PM" src="https://github.com/actions/actions-runner-controller/assets/162109584/511f18b6-4b90-4a78-b579-9f04caa06661">

I actually added the affinity parameters in a **custom values.yaml** and passed it while installing helm chart. Do let me know each of these 3 methods I used are accurate. 

Although I couldn't understand what is **container jobs in kubernetes mode** though. Could you point me to the correct documentation for me to go through?
