### ISSUE TITLE
ArtifactHub index for gha-runner-scale-set and gha-runner-scale-set-controller

### ISSUE THREAD

**Issue by Hazmi35** [actions/actions-runner-controller#3357]
### What would you like added?
The new helm charts for AutoScaling Runner ScaleSets to be published on ArtifactHub

### Why is this needed?
Better discoverability and as the old [actions-runner-controller](https://artifacthub.io/packages/helm/actions-runner-controller/actions-runner-controller) is already on ArtifactHub, but not AutoScaling Runner ScaleSets. 

The README on this repo even had the artifacthub badge, but only for the  `actions-runner-controller`.

### Additional context
See https://github.com/actions/actions-runner-controller/issues/1502

**Comment by nikola-jokic** [comment]
Hey @Hazmi35,

This feature request is not related to the community version, but rather to the `gha-runner-scale-set`. Please follow the issue template and submit the feature request related to the `gha-runner-scale-set` on the [GitHub Community Support Forum ](https://github.com/orgs/community/discussions/categories/actions)
