### ISSUE TITLE
Unable to run in high-availability mode

### ISSUE THREAD

**Issue by joshuabaird** [actions/actions-runner-controller#3382]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

ArgoCD

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Install a new deployment of ARC in a new cluster with a unique `runnerGroup` and the same `runnerScaleSetName` as an existing ARC Deployment
2. See this error in the new ARC deployment's listener log:


platform-utility-754b578d-listener autoscaler 2024-03-25T16:49:04Z      INFO    auto_scaler     unable to create message session. Will try again in 30 seconds  {"error": "409 - had issue communicating with Actions backend: The runner scale set platform-utility already has an active session for owner platform-utility-754b578d-listener."}
```

In this log from the new ARC instance, "platform-utility-754b578d-listener" is the name of the listener on the old instance.

### Describe the bug

I'm trying to deploy an HA instance of ARC in a new cluster following [these](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#high-availability-and-automatic-failover) instructions.

My first instance of ARC scalesets (which is already running) uses this config:

```
runnerGroup: platform-use1-utility-01
runnerScaleSetName: platform-utility
```

My second instance of ARC scalesets uses this config:

```
runnerGroup: platform-use1-sandbox-01
runnerScaleSetName: platform-utility
```

As described in the docs, they have the same `runnerScaleSetName` but different `runnerGroups`.  

In this configuration, the listener on the new/second instance of ARC fails to start with the following error:

```
2024-03-25T16:52:01Z      INFO    auto_scaler     unable to create message session. Will try again in 30 seconds  {"error": "409 - had issue communicating with Actions backend: The runner scale set platform-utility already has an active session for owner platform-utility-754b578d-listener."}
```

`platform-utility-754b578d-listener` is the name of the listener on the first instance of ARC.  It seems the two can not co-exist with each other.

What am I doing incorrectly here?

### Describe the expected behavior

The listener should start on the second instance of ARC and GH should distribute jobs across the first and second instances.

### Additional Context

```yaml
N/A
```

### Controller Logs

```shell
N/A
```

### Runner Pod Logs

```shell
N/A
```

**Comment by joshuabaird** [comment]
I just noticed that the second instance of ARC just came online (no changes were made) -- but now both runners are configured in the same runner group -- even though the second instance of ARC is configured to be in a separate runner group (`platform-use1-sandbox-01`):

![image](https://github.com/actions/actions-runner-controller/assets/6271918/1dbc104d-5c31-44d5-b971-df934edfa138)

In this configuration (runner groups are apparently the same) -- jobs seem to be getting distributed across both workers. This contradicts what is in the documentation -- so I'm a bit confused.

**Comment by nikola-jokic** [comment]
Hey @joshuabaird,

I'm failing to reproduce the issue. Can you please post the output of the `kubectl get autoscalingrunnersets -n $NS -o yaml` for both of your scale sets? I created 2 kind clusters, applied controllers on both of them and installed scale sets with different runner groups. 
![image](https://github.com/actions/actions-runner-controller/assets/97525037/adea11a0-4add-42d0-81ae-468435265cc5)
![image](https://github.com/actions/actions-runner-controller/assets/97525037/8fadcdec-30a8-4f40-9dff-c537c2a1a46d)

**Comment by nikola-jokic** [comment]
Closing this one until we hear back from you :relaxed: Please let us know if this issue is resolved.

**Comment by nisaanthN** [comment]
@joshuabaird Would be greatly helpful if you could confirm that your issue is resolved. Our team is planning to adopt the high availability mode. Thank you.

**Comment by SolverDude** [comment]
> Hey [@joshuabaird](https://github.com/joshuabaird),
> 
> I'm failing to reproduce the issue. Can you please post the output of the `kubectl get autoscalingrunnersets -n $NS -o yaml` for both of your scale sets? I created 2 kind clusters, applied controllers on both of them and installed scale sets with different runner groups. ![image](https://github.com/actions/actions-runner-controller/assets/97525037/adea11a0-4add-42d0-81ae-468435265cc5) ![image](https://github.com/actions/actions-runner-controller/assets/97525037/8fadcdec-30a8-4f40-9dff-c537c2a1a46d)

@nikola-jokic , I've fallen into a similar trap as the original poster.  Do you have a means to share what values.yaml you provided in your working scenario?

**Comment by madAndroid** [comment]
We've also been experiencing problems with this, and CoPilot has suggested using a Github App for auth, instead of a PAT token - can anyone verify whether this is true? the docs here: [high-availability-and-automatic-failover](https://docs.github.com/en/actions/tutorials/use-actions-runner-controller/deploy-runner-scale-sets) - don't mention not being able to use a PAT token for the auth

**Comment by bsr-blinkit** [comment]
@SolverDude  @joshuabaird  Did you folks install both the runner-scale-sets on the same kubernetes namespace?
