### ISSUE TITLE
The listener pod for gha-runner-scale-set is not running after a while 

### ISSUE THREAD

**Issue by ashihadeh-boku** [actions/actions-runner-controller#3408]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Deploy controller with fluxcd 

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/actions/actions-runner-controller-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: runner-scale-set-controller
  namespace: arc-system
spec:
  interval: 1m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-arc-runner
  namespace: arc-runners
spec:
  interval: 1m
  chart:
    spec:
      chart: gha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 1m
  values:
    githubConfigUrl: https://github.com/my-org/
    githubConfigSecret: my-org-github-actions-runner-token

```

- After 5-10 days the my-arc-runner-listener pod is not available in the cluster and there are no logs in the controller related to this action. I found a workaround to fix the situation by deleting the arc-runners helmrelease and reinstall it. 

  it seems that the my-arc-runner-listener has no replica set/deployment/statefulset attached to it so it can recover if the pod is deleted from the cluster.
```


### Describe the bug

After 5-10 days the my-arc-runner-listener pod is not available in the cluster and there are no logs in the controller related to this action. I found a workaround to fix the situation by deleting the arc-runners helmrelease and reinstall it. 

  it seems that the my-arc-runner-listener has no replica set/deployment/statefulset attached to it so it can recover if the pod is deleted from the cluster. 


### Describe the expected behavior

my-arc-runner-listener is always running to be able to create runners 

### Additional Context

```yaml
nothing
```

### Controller Logs

```shell
nothing
```

### Runner Pod Logs

```shell
nothing
```

**Comment by nikola-jokic** [comment]
Hey @ashihadeh-boku,

I'm not sure we can do anything about this without logs.

The listener should be re-created every time it exits. There is a AutoscalingListener controller monitoring the state of the listener pod. I'm not sure how to reproduce this issue or fix it without the listener log and the controller log.

Having said that, it is very strange that the controller log is empty. It may be something that is related to the cluster, that caused this problem?

**Comment by samip5** [comment]
This happens every time on upgrade as well, aka somehow my runner sets are missing, and there's no listening pods either. I think it's related to this issue.

I also use FluxCD the same way as OP to deploy it and I got for some reason errors in the controller about k8s API, that went away by restarting it, however no listener pod.

For reference:
```
E0331 22:09:00.904506       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1alpha1.AutoscalingRunnerSet: the server is currently unable to handle the request (get autoscalingrunnersets.actions.github.com)
E0331 22:09:03.163678       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1alpha1.EphemeralRunnerSet: the server is currently unable to handle the request (get ephemeralrunnersets.actions.github.com)
E0331 22:09:05.020267       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.RoleBinding: the server is currently unable to handle the request (get rolebindings.rbac.authorization.k8s.io)
E0331 22:09:05.086189       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.ServiceAccount: the server is currently unable to handle the request (get serviceaccounts)
E0331 22:09:05.616373       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.Role: the server is currently unable to handle the request (get roles.rbac.authorization.k8s.io)
E0331 22:09:05.834721       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.Pod: the server is currently unable to handle the request (get pods)
E0331 22:09:06.982203       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1alpha1.EphemeralRunner: the server is currently unable to handle the request (get ephemeralrunners.actions.github.com)
E0331 22:09:06.986014       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1alpha1.AutoscalingListener: the server is currently unable to handle the request (get autoscalinglisteners.actions.github.com)
```

**Comment by nikola-jokic** [comment]
I think there is an error in your upgrade process. This error indicated that CRDs are not installed, so the controller cannot install the reflector. There must be an issue in the upgrade process that removes the CRDs, and when you re-install, new CRDs are not installed with it

**Comment by samip5** [comment]
> I think there is an error in your upgrade process. This error indicated that CRDs are not installed, so the controller cannot install the reflector. There must be an issue in the upgrade process that removes the CRDs, and when you re-install, new CRDs are not installed with it

I doubt that as just deleting the pod takes care of not having those errors anymore.

Due to the amount of finalisers, this is also hard to uninstall via Helm to begin with but CRDs are handled via Helm, not seperately.

**Comment by singhujjwal** [comment]
After 10 days to upgrade to this version my runners stopped running any new jobs, was running fine till yesterday night.
Tried everything by unintalling removing CRDs and reinstalling, everything seems fine but on checking 
`ephemeralrunners.actions.github.com` it says the Pod failed 5 times.
I don't know what is failing.

Dont have much information either from that
<img width="702" alt="image" src="https://github.com/actions/actions-runner-controller/assets/4547765/9b5f7f81-8dae-45ae-b4fb-14e7e4fde61c">

**Comment by nikola-jokic** [comment]
@samip5 Maybe it was a temporary error. When the controller is started, it fails to talk to the kubernetes API. Then either another replica becomes the master, and it starts talking to the API, or the pod is re-scheduled. I'm not sure, but the controller can't even start. I would look into the cluster. The error is happening with client-go, so the controller cannot fetch objects.

@singhujjwal What version of the controller are you using? There must be a reason recorded in the controller log, so you may want to inspect that :relaxed:

**Comment by samip5** [comment]
> @samip5 Maybe it was a temporary error. When the controller is started, it fails to talk to the kubernetes API. Then either another replica becomes the master, and it starts talking to the API, or the pod is re-scheduled. I'm not sure, but the controller can't even start. I would look into the cluster. The error is happening with client-go, so the controller cannot fetch objects.

Which went away after deleting the pod, as I said. Now it works again, but that happens often on upgrades which I don't think it should.

**Comment by nikola-jokic** [comment]
Don't get me wrong, it shouldn't, but there is nowhere in ARC where we can control this.
This issue is raised before we are able to start working on it. That is why I pointed out that it may be related to something on the cluster.

**Comment by singhujjwal** [comment]
I had an old runner image which was not supported, had to cleanup the ephemeralrunners to get the pod and it's logs to figure it out

```
RUNNER 2024-04-10 04:43:10Z INFO Runner] Deleting Runner Session...
[RUNNER 2024-04-10 04:43:10Z ERR  Terminal] WRITE ERROR: An error occured: Runner version v2.313.0 is deprecated and cannot receive messages.
An error occured: Runner version v2.313.0 is deprecated and cannot receive messages.
[RUNNER 2024-04-10 04:43:10Z ERR  Listener] GitHub.DistributedTask.WebApi.AccessDeniedException: Runner version v2.313.0 is deprecated and cannot receive messages.
[RUNNER 2024-04-10 04:43:10Z ERR  Listener]    at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
```
Thanks for the help
