### ISSUE TITLE
AutoscalingRunnerSet CRD is too big to install via ArgoCD, requires annotation

### ISSUE THREAD

**Issue by rteeling-evernorth** [actions/actions-runner-controller#3415]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.7.0,0.8.2,0.9.0

### Deployment Method

ArgoCD

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Install the chart via ArgoCD with the Custom Resource Definitions
```

### Describe the bug

The AutoscalingRunnerSet Custom Resource Definition is too large to be installed via ArgoCD. 

### Describe the expected behavior

The CRD should install with the rest of the helm chart

### Additional Context

```yaml
This can be easily fixed by adding the annotation `argocd.argoproj.io/sync-options: Replace=true`. This annotation should be inert outside of ArgoCD.

I can open a pull request upon request, however I am not sure how people feel about adding this.
```

### Controller Logs

```shell
N/A - The controller cannot start without the CRD installed
```

### Runner Pod Logs

```shell
N/A
```

**Comment by nikatar** [comment]
I faced the same problem. 
```
one or more objects failed to apply, reason: CustomResourceDefinition.apiextensions.k8s.io "autoscalingrunnersets.actions.github.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes. Retrying attempt #5 at 8:40PM.
```
![image](https://github.com/actions/actions-runner-controller/assets/43474647/8d48b91b-257a-4031-ab0a-f7324961bd39)

**Comment by rteeling-evernorth** [comment]
@nikatar you can bandaid this for the moment by adding `argocd.argoproj.io/sync-options: Replace=true` to that crd's annotations, but i want to get this there by default

**Comment by nikatar** [comment]
Solution
https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/

```
    syncOptions:
      - ServerSideApply=true
```

**Comment by rteeling-evernorth** [comment]
Yeah, that will work too

**Comment by nikola-jokic** [comment]
Hey @rteeling-evernorth,

I don't think we can do anything about it. CRDs are generated, and bundled together. You should just use server side apply. As long as there is a way to install CRDs and the controller, I don't think we should change this.

**Comment by nikatar** [comment]
I think this issue can be closed

**Comment by DesmondH0** [comment]
I am wondering if [gha-runner-scale-set-controller](https://github.com/actions/actions-runner-controller/tree/master/charts/gha-runner-scale-set-controller) chart could support additional annotation to CRDs like [prometheus-operator-crds](https://github.com/prometheus-community/helm-charts/blob/008bad2a41f92f6ed07c0b096af486c9ebb11e72/charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml#L7-L9) chart does 🤔 

So user could easily add the server-side apply via helm values
