### ISSUE TITLE
Any documents for supporting Github Action Runner Scale Set with Windows

### ISSUE THREAD

**Issue by denny-snapone** [actions/actions-runner-controller#3419]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.0

### Deployment Method

ArgoCD

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Install ARC
2. Build docker image for Windows Runner
3. Set up Runner Scale Set for windows
```

### Describe the bug

The runner scale set cannot start working

### Describe the expected behavior

Should be working as Linux runner

### Additional Context

```yaml
EKS version 1.29 - Windows Server 2022
```

### Controller Logs

```shell
None
```

### Runner Pod Logs

```shell
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "53f10832067251a1f3e9cd50501df18ff8845a2e14c890453bbf21cd1e86ed2e": plugin type="vpc-bridge" name="vpc" failed (add): failed to parse Kubernetes args: failed to get pod IP address snpo-windows-gha-x64-latest-qfhlb-runner-dv4cx: error executing k8s connector: error executing connector binary: exit status 1 with execution error: pod snpo-windows-gha-x64-latest-qfhlb-runner-dv4cx does not have label vpc.amazonaws.com/PrivateIPv4Address
```

**Comment by nikola-jokic** [comment]
Hey @denny-snapone,

We don't officially support Windows runners with ARC. See [this](https://github.com/actions/actions-runner-controller/discussions/2880) discussion.
