### ISSUE TITLE
ServiceMonitor missing?

### ISSUE THREAD

**Issue by marekaf** [actions/actions-runner-controller#3525]
ServiceMonitor is missing in chart templates for the new controller even though a helper is mentioning it https://github.com/actions/actions-runner-controller/blob/a6d87c46cd01d5ded0c547793ead736fbdd47061/charts/gha-runner-scale-set-controller/templates/_helpers.tpl#L130

Are ServiceMonitor and Prometheus metrics supported in the new controller?

**Comment by marekaf** [comment]
@nikola-jokic but this is a feature request, I want that Service Monitor :D

**Comment by nikola-jokic** [comment]
Hey @marekaf,

Feature requests for gha-runner-scale-set should be submitted to the Community Support Forum. I would normally close this issue with this message, but you provided enough information so I wanted to close it with the PR and write a message later. Sorry I didn't write the message sooner...

![image](https://github.com/actions/actions-runner-controller/assets/97525037/271314c9-8114-4164-a1a5-8457a6161fb5)

**Comment by mnacharov** [comment]
FYI: https://github.com/orgs/community/discussions/118627
