### ISSUE TITLE
Ephemeral runner gets stuck in Successful state

### ISSUE THREAD

**Issue by katarzynainit** [actions/actions-runner-controller#3527]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. I have ARC installed in GKE in one namespace: controller and runnersets in the same one
2. All works as expected in most of the cases
3. From time to time (randomly) we observe such behavior:
- ephemeral runnerset gets patch , e.g. from 0 desired to 1 replica
- ephemeral runner is created, but immediately its status is changed to Succeeded and nothing happens - the workload is "stuck" on waiting for runner
```

### Describe the bug

In controller logs I see that it already "Found the runner with the same name" - it looks like the controller is performing reconcile twice for the same ephemeralrunner in almost the same time, the second run "removes" runner and makes it hung.

The runner is eventually not created, and the ephemeral runner gets to stage Succeeded and stuck until workflow is cancelled. 

We started to observe this behavior when we moved to faster cluster. 

### Describe the expected behavior

The controller should create runner always on ephemeral runner creation. 

### Additional Context

```yaml
N/A
```

### Controller Logs

```shell
https://gist.github.com/katarzynainit/ceccccde10d5454aa104d0f5a98f9b0d
```

### Runner Pod Logs

```shell
N/A
```

**Comment by nikola-jokic** [comment]
Hey @katarzynainit,

Can you please show the controller values.yaml file, so I can try to reproduce this issue.

**Comment by katarzynainit** [comment]
Hi, we are using forked arc-controller - code changes relate to skipping controller and listeners SA and RBAC creation based on three flags.
Code related to processing ephemeral runners is unchanged vs 0.9.0. 

https://gist.github.com/katarzynainit/d9e6ed4d3c6b95e929d73e2b1e8f7cc1 (flags for internal changes are marked in the values)

We started to observe this issue on faster cluster, we didn't see them before (the same configuration, but different and slower cluster). 

It also happens from time to time only, so might be difficult to observe.
