### ISSUE TITLE
Override the init-dind-externals init container in the runner set helm chart

### ISSUE THREAD

**Issue by ecooke-macu** [actions/actions-runner-controller#3572]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Create a values.yaml
Specify init container for init-dind-externals
```

### Describe the bug

The default init-dind-externals container doesn't get overwritten and is stuck on the default.

### Describe the expected behavior

Able to override the init-dind-externals container

### Additional Context

```yaml
We need to stop the logging of all files copied. Currently it logs about 20k lines each time the container starts. We need to remove the `-v` from the `cp`.
```

### Controller Logs

```shell
Org policies don't allow internal logs to be publicly available. I can provide them privately though.
```

### Runner Pod Logs

```shell
Org policies don't allow internal logs to be publicly available. I can provide them privately though.
```

**Comment by nikola-jokic** [comment]
Hey @edwardcookemacu,

Please refer to my comment [here](https://github.com/actions/actions-runner-controller/issues/3571#issuecomment-2146966547). This behavior is well documented and explained in various links I linked. Closing this issue now.

**Comment by ecooke-macu** [comment]
Thank you! That pointed me in the right direction.
