### ISSUE TITLE
actions cache not actually working

### ISSUE THREAD

**Issue by davhdavh** [actions/actions-runner-controller#3582]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.1

### Deployment Method

ArgoCD

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. run workflow, notice the "Set up job" section contains lines similar to this:
Download action repository 'actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3' (SHA:4d6c8fcf3c8f7a60068d26b594648e99df24cee3)
2. run workflow again. Notice it has the same lines
```

### Describe the bug

The problem is that `_work` folder is totally reset every time(since it's ephemeral), but the actions cache is specified as living in `_work/actions` and thus does not survive until the next run.

### Describe the expected behavior

Either of these would solve the problem:
* https://github.com/actions/runner/issues/3316
* `_work/actions` is not reset across runs

### Additional Context

```yaml
NA
```

### Controller Logs

```shell
NA
```

### Runner Pod Logs

```shell
NA
```

**Comment by nikola-jokic** [comment]
This issue is related to the runner, so I'm closing this one here.

**Comment by davhdavh** [comment]
now possible with https://github.com/marketplace/actions/save-actions-cache
