### ISSUE TITLE
actions-runner | docker-compose-plugin pre-install

### ISSUE THREAD

**Issue by rking-bennie** [actions/actions-runner-controller#3654]
### What would you like added?

We were using the old github runners which come installed with docker & docker-compose. In upgrading to this action-runner-controller, docker-compose plugin is not installed which means we need to build an image on top to include this plugin. In future versions could docker-compose-plugin come pre-installed?

Note: Feature requests to integrate vendor specific cloud tools (e.g. `awscli`, `gcloud-sdk`, `azure-cli`) will likely be rejected as the Runner image aims to be vendor agnostic.

### Why is this needed?

Simply migration and build process on app teams using actions/actions-runner

*A clear and concise description of any alternative solutions or features you've considered.*

We have built a new image with this plugin installed for now

**Comment by rking-bennie** [comment]
I put this on wrong repo. this was meant for the new action-controller

**Comment by sigurdfalk** [comment]
@rking-bennie Could you share how you install docker and docker-compose in a new image suitable for usage with the new actions controller? 🙏🏻
