### ISSUE TITLE
This self-hosted runner is currently using runner version 2.317.0. This version is out of date. Please update to the latest version 2.319.1

### ISSUE THREAD

**Issue by bmike78** [actions/actions-runner-controller#3721]
### What would you like added?

Can we get a new release?

### Why is this needed?

Github actions showing the following warning:

This self-hosted runner is currently using runner version 2.317.0. This version is out of date. Please update to the latest version 2.319.1

### Additional context

*Add any other context or screenshots about the feature request here.*

**Comment by bmike78** [comment]
@nikola-jokic, just FYI if you can take a look at push a new release with updated runner: https://github.com/actions/actions-runner-controller/pull/3708

**Comment by Lucas-Hughes** [comment]
@bmike78 looks like there was an update sometime recently to the existing chart. Using 0.9.3 helm chart, and my runners are now utilizing the latest version (2.319.1), removing the warning message post job.
