### ISSUE TITLE
Cannot start docker and prettier action failing

### ISSUE THREAD

**Issue by marcelmedeiros1** [actions/actions-runner-controller#3778]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

ArgoCD

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Go to actions
2. Run 'gruntwork-io/terragrunt-action@v2' and 'creyD/prettier_action@v4.3' in a self hosted runner
```

### Describe the bug

The terragrunt action gives me the following error:
`ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

The prettier action gives me the following error:
```
Installing prettier...
/actions-runner/_work/_actions/creyD/prettier_action/v4.3/entrypoint.sh: line 50: npm: command not found
```

### Describe the expected behavior

The set up of these actions should work, like in the "ubuntu-latest" runners.

### Additional Context

```yaml
spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
```

### Controller Logs

```shell
------
```

### Runner Pod Logs

```shell
-------
```

**Comment by chrispat** [comment]
Thank you for your issue.

There is no expectation that the basic image provided as part of ARC is a drop-in replacement for what is provided by GitHub Hosted Runners.  If you need specific tools like npm available to your CI you should either use the appropriate setup-* action that would install it or add it to your own based container image.  

In the case of actions like `gruntwork-io/terragrunt-action` that are implemented as an on demand container build with a docker file these are not supported in ARC.
