### ISSUE TITLE
Runner pods start and immediately die.

### ISSUE THREAD

**Issue by grantzukeltillster** [actions/actions-runner-controller#905]
When I deploy the runners they start and run for about 15 seconds and then immediately terminate if I'm running a job or not.

What i'm running to install the runner system.

```
kubectl create namespace actions-runner-system

kubectl create secret generic controller-manager -n actions-runner-system --from-literal=github_token=${GIT_PAT_TOKEN}

kubectl apply -n actions-runner-system -f https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.14.0/actions-runner-controller.yaml 
```

The Runner Deployment
```---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: tillster-organization-github-action-runner
  namespace: actions-runner-system
spec:
  replicas: 5
  template:
    spec:
      labels:
        - tillster-self-hosted
      organization: tillster
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "8.0"
          memory: "16Gi"
        requests:
          cpu: "1.0"
          memory: "1Gi"
      ephemeral: false
      dockerMTU: 1500
      dockerEnabled: true
      workDir: /home/runner/work
      dockerdContainerResources:
        limits:
          cpu: "8.0"
          memory: "16Gi"
        requests:
          cpu: "1.0"
          memory: "1Gi"
```
![image](https://user-images.githubusercontent.com/81576382/138190767-ec83254c-edfb-43e8-b1e0-a137f72768d9.png)

![image](https://user-images.githubusercontent.com/81576382/138190785-04315adf-3937-4df9-95f8-2d405f1a4574.png)

![image](https://user-images.githubusercontent.com/81576382/138191063-0d1ccb1e-ea4b-4fd1-a1ac-4abcb96b3d21.png)

Describe output of one of the nodes that is terminating.

```
kubectl describe pods tillster-organization-github-action-runner-kd82s-v5plp -n actions-runner-system


Name:                      tillster-organization-github-action-runner-kd82s-v5plp
Namespace:                 actions-runner-system
Priority:                  0
Node:                      ip-10-160-32-232.ec2.internal/10.160.32.232
Start Time:                Wed, 20 Oct 2021 18:38:24 -0600
Labels:                    runner-template-hash=7d858889c7
Annotations:               kubernetes.io/psp: eks.privileged
Status:                    Terminating (lasts <invalid>)
Termination Grace Period:  30s
IP:                        
IPs:                       <none>
Controlled By:             Runner/tillster-organization-github-action-runner-kd82s-v5plp
Containers:
  runner:
    Container ID:   
    Image:          summerwind/actions-runner:latest
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     8
      memory:  16Gi
    Requests:
      cpu:     1
      memory:  1Gi
    Environment:
      RUNNER_NAME:                                         tillster-organization-github-action-runner-kd82s-v5plp
      RUNNER_ORG:                                          tillster
      RUNNER_REPO:                                         
      RUNNER_LABELS:                                       tillster-self-hosted
      RUNNER_GROUP:                                        
      RUNNER_TOKEN:                                        ATOMDPQSXD55QOWREDCNCR3BOC3JY
      DOCKERD_IN_RUNNER:                                   false
      GITHUB_URL:                                          https://github.com/
      RUNNER_WORKDIR:                                      /home/runner/work
      DOCKER_HOST:                                         tcp://localhost:2376
      DOCKER_TLS_VERIFY:                                   1
      DOCKER_CERT_PATH:                                    /certs/client
      NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME:          tillster-shared-eks
      NEW_RELIC_METADATA_KUBERNETES_NODE_NAME:              (v1:spec.nodeName)
      NEW_RELIC_METADATA_KUBERNETES_NAMESPACE_NAME:        actions-runner-system (v1:metadata.namespace)
      NEW_RELIC_METADATA_KUBERNETES_POD_NAME:              tillster-organization-github-action-runner-kd82s-v5plp (v1:metadata.name)
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_NAME:        runner
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_IMAGE_NAME:  summerwind/actions-runner:latest
    Mounts:
      /certs/client from certs-client (ro)
      /home/runner/work from work (rw)
      /runner/externals from externals (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rx5r5 (ro)
  docker:
    Container ID:   
    Image:          docker:dind
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      DOCKER_TLS_CERTDIR:                                  /certs
      NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME:          tillster-shared-eks
      NEW_RELIC_METADATA_KUBERNETES_NODE_NAME:              (v1:spec.nodeName)
      NEW_RELIC_METADATA_KUBERNETES_NAMESPACE_NAME:        actions-runner-system (v1:metadata.namespace)
      NEW_RELIC_METADATA_KUBERNETES_POD_NAME:              tillster-organization-github-action-runner-kd82s-v5plp (v1:metadata.name)
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_NAME:        docker
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_IMAGE_NAME:  docker:dind
    Mounts:
      /certs/client from certs-client (rw)
      /home/runner/work from work (rw)
      /runner/externals from externals (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rx5r5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  work:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  externals:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  certs-client:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-rx5r5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-rx5r5
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  18s   default-scheduler  Successfully assigned actions-runner-system/tillster-organization-github-action-runner-kd82s-v5plp to ip-10-160-32-232.ec2.internal
  Normal  Pulled     17s   kubelet            Container image "summerwind/actions-runner:latest" already present on machine
  Normal  Created    17s   kubelet            Created container runner
  Normal  Started    16s   kubelet            Started container runner
  Normal  Pulled     16s   kubelet            Container image "docker:dind" already present on machine
  Normal  Created    16s   kubelet            Created container docker
  Normal  Started    16s   kubelet            Started container docker```

Controller Logs
```
2021-10-21T00:42:13.421Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runner", "request": "actions-runner-system/tillster-organization-github-action-runner-kd82s-fp2lh"}
2021-10-21T00:42:13.421Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runner", "request": "actions-runner-system/tillster-organization-github-action-runner-kd82s-v5plp"}
2021-10-21T00:42:13.421Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Runner","namespace":"actions-runner-system","name":"tillster-organization-github-action-runner-kd82s-fp2lh","uid":"e2644306-27e6-45f3-b3c4-99bb7ba10175","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"486055"}, "reason": "PodCreated", "message": "Created pod 'tillster-organization-github-action-runner-kd82s-fp2lh'"}
2021-10-21T00:42:13.892Z	INFO	controllers.Runner	Deleted runner pod	{"runner": "actions-runner-system/tillster-organization-github-action-runner-kd82s-fp2lh", "repository": ""}
2021-10-21T00:42:13.892Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runner", "request": "actions-runner-system/tillster-organization-github-action-runner-kd82s-fp2lh"}
2021-10-21T00:42:13.892Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Runner","namespace":"actions-runner-system","name":"tillster-organization-github-action-runner-kd82s-fp2lh","uid":"e2644306-27e6-45f3-b3c4-99bb7ba10175","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"486055"}, "reason": "PodDeleted", "message": "Deleted pod 'tillster-organization-github-action-runner-kd82s-fp2lh'"}
2021-10-21T00:42:14.269Z	INFO	controllers.Runner	Deleted runner pod	{"runner": "actions-runner-system/tillster-organization-github-action-runner-kd82s-fp2lh", "repository": ""}
2021-10-21T00:42:14.269Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runner", "request": "actions-runner-system/tillster-organization-github-action-runner-kd82s-fp2lh"}
2021-10-21T00:42:14.269Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runner", "request": "actions-runner-system/tillster-organization-github-action-runner-kd82s-fp2lh"}
2021-10-21T00:42:14.269Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Runner","namespace":"actions-runner-system","name":"tillster-organization-github-action-runner-kd82s-fp2lh","uid":"e2644306-27e6-45f3-b3c4-99bb7ba10175","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"486055"}, "reason": "PodDeleted", "message": "Deleted pod 'tillster-organization-github-action-runner-kd82s-fp2lh'"}
```

I'm not really seeing why the pods keep terminating and re-creating can someone help me here?

**Comment by mumoshu** [comment]
@grantzukeltillster Hey! I don't think this can be triggered by actions-runner-controller alone. In other words, I think this is due to some external controller in your cluster is interfering with actions-runner-controller.

Do you have any mutating webhook that modifies runner pod spec? Then actions-runner-controller may think that it needs to recreate the pod, which explains what you see.

Otherwise, do you have any security agent that automatically detects and terminates any pod that doesn't meet your compliance rules? That might also explains your issue.

If you have no idea what's going on, you'd probably take your K8s apiserver audit log so that you can see who's terminating pods. That may help isolating the cause.

**Comment by toast-gear** [comment]
> I'm not really seeing why the pods keep terminating and re-creating can someone help me here?

This behaviour is normally because something outside of actions-runner-controller is changing the runners pod spec and so the controller thinks something has changed as the spec doesn't match so it terminates the pod and reprovisions it. The pod spec is then changed again and so the controller terminates and reprovisions the pod etc etc
